### ISSUE TITLE
With statement can not work in vertica.sql magic in jupyter notebook

### ISSUE THREAD

**Issue by dingqiangliu** [vertica/VerticaPy#102]
Hi, 
It look with statement can not work in vertica.sql magic in jupyter notebook at VerticaPy 0.6.1

![with_statement_can_not_work_in_vertica sql_magic](https://user-images.githubusercontent.com/15042360/118137780-2c570200-b438-11eb-99a9-6c7a49b9da11.png)

**Comment by oualib** [comment]
Thank you DQ. It will be corrected on v0.6.2

**Comment by oualib** [comment]
Solved in v0.6.2, the doc will be soon released.
