### ISSUE TITLE
topk() on Varchar with empty and missing values

### ISSUE THREAD

**Issue by julienfournel** [vertica/VerticaPy#104]
When a topk() is performed on a Varchar with empty and missing values, then results are wrong.
![Topk](https://user-images.githubusercontent.com/84398497/118783888-ca5f2800-b88f-11eb-802f-62b2043a3a9f.png)

**Comment by oualib** [comment]
Hi Julien,
Can you please give your version?
Thanks

**Comment by oualib** [comment]
Hi Julien,
The issue is corrected and will be available in v0.6.2.
It seems the problem comes from SUMMARIZE_CATCOL which is not handling correctly empty strings.

**Comment by oualib** [comment]
Solved in v0.6.2, the doc will be soon released.
