### ISSUE TITLE
Ingest pandas DataFrame/csv/json using temporary table

### ISSUE THREAD

**Issue by iamdionysus** [vertica/VerticaPy#106]
The current implementation of https://www.vertica.com/python/documentation_last/utilities/pandas_to_vertica/ and others I mentioned above use a schema(default public) to ingest DataFrame/csv/json in the table. But, for a sandbox stage, it would be nice if VerticaPy has a feature to use the temporary table that Vertica supports. It will be helpful especially on the sandbox stage because 1) it reduces the cost to manage temporary table names, 2) it removes write permission management cost.

**Comment by oualib** [comment]
That's a great recommendation. We will add the possibility to create LOCAL TEMP TABLE in the read_csv, read_json so users can work more in a pandas way. We will add this in v0.6.2

**Comment by oualib** [comment]
The features is available in v0.6.2, the doc will be soon released.
