### ISSUE TITLE
In asfreq function, bffill = TS_FIRST_VALUE, ffill = TS_LASTVALUE, shouldn't it be the opposite way?

### ISSUE THREAD

**Issue by iamdionysus** [vertica/VerticaPy#107]
When I use `ffil`l in `asfreq`'s method parameter, I would expect it would do the same as `ffill` in pandas DataFrame when I run fillna. However, VerticaPy's vDataFrame is getting the opposite result in asfreq. 

https://github.com/vertica/VerticaPy/blob/c4e8b74c53104bf72000cc44559232fbb269bff3/verticapy/vdataframe.py#L3021-L3036

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html#pandas.DataFrame.fillna

**Comment by oualib** [comment]
Hi, you are right. It will be corrected in the v0.6.2.

**Comment by oualib** [comment]
Solved in v0.6.2, the doc will be soon released.
