### ISSUE TITLE
Unable to use case_when function properly

### ISSUE THREAD

**Issue by SMoazzamR** [vertica/VerticaPy#11]
I am trying to use case_when function and able to replace the values where conditions are met but as per the CASE statement, we have to specify the ELSE part which verticapy allows to mention within other parameters. The issue is that, if I want to use other values unchanged I have to specify the column name as it is like we did in SQL case statement but vertica is automatically using /' before and after when creating its SQL thus throwing error.

**Comment by oualib** [comment]
Hi @SMoazzamR,

Have you tried setting the auto_quote parameter to False in order to enter pure SQL ? In this case if you want a string as a condition you'll have to write "'value'".

**Comment by SMoazzamR** [comment]
Thanks, Issue is resolved if I want to use the value of column in ELSE part then I have to use like others="column1" and in conditions={'a<b':"'hardcode value'"}
