### ISSUE TITLE
Type hint for union type in method/function def

### ISSUE THREAD

**Issue by iamdionysus** [vertica/VerticaPy#112]
https://github.com/vertica/VerticaPy/blob/659884905b11cf3f8c69fe93a02946cb5c943347/verticapy/vdataframe.py#L9091

Under the python [documentation](https://docs.python.org/3/library/typing.html) it looks like the union type should be `Union[dict, list]`. I am not 100% sure `(dict, list)` is also allowed but when you have time, can you check this out?

**Comment by oualib** [comment]
Indeed, it will be corrected in the v0.6.3,
Thanks again for noticing it!

**Comment by oualib** [comment]
It is corrected and it is already available in the main folder. It will be pushed to Pypi when the 0.6.3 is implemented.
