### ISSUE TITLE
AutoML issue on 0.6.2

### ISSUE THREAD

**Issue by kryeziuj** [vertica/VerticaPy#113]
AutoML is only testing NaiveBayes and LogisticRegression for binary classification while the estimator parameter is 'native'! This is only happening in the new version 0.6.2 - in 0.6.1 it was correctly testing all native models from Vertica.

**Comment by oualib** [comment]
It will be corrected in the next release. It is still possible to pass a list of the different models to use. Otherwise, you can downgrade to 0.6.1 and wait for 0.6.3.

**Comment by oualib** [comment]
It is corrected and it is already available in the main folder. It will be pushed to Pypi when the 0.6.3 is implemented.
