### ISSUE TITLE
'hchart' parameter aggregate not working

### ISSUE THREAD

**Issue by kryeziuj** [vertica/VerticaPy#122]
when plotting barchart, for unique 'x' and 'y' without needing to aggregate, the aggregate=False doesn't help to only plot x and y. Instead it is necessary to do some meaningless aggregate over 1 value like AVG(x) as x. Example:
data.hchart(x = "xx",
               y = "yy",
               aggregate = False) doesn't work, instead it is needed to do:
data.hchart(x = "xx",
               y = "AVG(yy) AS yy",
               aggregate = True/False)

**Comment by oualib** [comment]
It is corrected and it is already available in the main folder. It will be pushed to Pypi when the 0.6.3 is implemented.
