### ISSUE TITLE
read_csv bug

### ISSUE THREAD

**Issue by VerticaDataScientist** [vertica/VerticaPy#1317]
### What is the requested change?

`read_csv` function doesn't copy the data into the table correctly for a csv file, however, the generated query is correct and it worked when I use only SQL. This issue is observed on version 1.0.3, 1.0.4 and 1.0.5

**Comment by oualib** [comment]
The bug will be resolved in this PR: https://github.com/vertica/VerticaPy/pull/1322.

Please use ``record_terminator=None`` to ingest your dataset successfully.

A clear warning message has been added.
