### ISSUE TITLE
read_csv - Automatic choice of data types is problematic

### ISSUE THREAD

**Issue by mail4umar** [vertica/VerticaPy#1318]
### What is the requested change?

Sometimes, the simple choice of data type for ingesting data is wrong by default. 

For the smart meter dataset, when we try to import the `sm_consumption.csv` file, it gets the wrong data type for `value` column. This results in empty values of the `value` column. The default data type is Numeric(12). Though it should be able store all the values in the dataset, but it fails to.

But if i manually provide the data type to be Float(22), it works.

```
sm_consumption = vp.read_csv(
    "sm_consumption.csv",
    dtype = {
        "meterID": "Integer",
        "dateUTC": "Timestamp(6)",
        "value": "Float(22)",
    }
)
```

The same is true for `sm_weather.csv` file ingestion in the same dataset.

**Comment by oualib** [comment]
In my computer the ingestion works well. It seems the CSV is not standard and you should use '"' to enclose your strings. The data types are determined with flex table. For more precision, please use the 'parse_n_rows' parameter.
