### ISSUE TITLE
vColumn is not added to dataframe for KNN Regressor/Classifier

### ISSUE THREAD

**Issue by liv4unix** [vertica/VerticaPy#134]
The following "knnclass_predict" column appears only when the predict output is returned (for both the regressor and classifier); however, the vColumn is not actually added to the Vertica DataFrame, as with other models (XGBoost and KMeans, for instance).  The same issue occurs with DBSCAN also (not shown in this issue submission).

CLASSIFIER
#knnclass_model = KNeighborsClassifier(name = "stocks_interday_knnclass")
knnclass_model.predict(cluster_vdf, 
              name = "knnclass_predict")

REGRESSOR
#knnregr_model = KNeighborsRegressor("stocks_interday_knn_regr",
                                    n_neighbors = 2)
knnregr_model.predict(stocks_vdf, name=("knn_regr_predict"))

I have tried adding "inplace = True", but the option has no effect for KNN operations. 

Thanks for the help!
Theresa

**Comment by oualib** [comment]
Please write:
stocks_vdf = knnregr_model.predict(stocks_vdf, name=("knn_regr_predict"))
KNN is an extended model and does not have an inplace option. We can add it in v0.6.3.

**Comment by liv4unix** [comment]
Thank you Badr, that worked.
Theresa
 #134 <https://github.com/vertica/VerticaPy/issues/134> is resolved.
