### ISSUE TITLE
Method to simultaneously create VDF when creating Vertica Table from Pandas 

### ISSUE THREAD

**Issue by liv4unix** [vertica/VerticaPy#135]
Is it possible to simultaneously create a Vertica DataFrame when creating a Vertica Table from a Pandas DataFrame?  I am unable to find a way to this?  Right now, this requires multiple steps:

#Pandas Dataframe to Vertica Table Creation:
pandas_to_vertica(cluster_df, name = "stocks_interday_cluster")

#Vertica DataFrame creation from Vertica Table:
cluster_vdf = vDataFrame('"stocks_interday_cluster"')

It seems like there should be method/switch/option to combine these 2 steps into one, for the sake of code efficiency.

Thanks!
Theresa

**Comment by oualib** [comment]
Please try to display your version when raising an error.
Since 0.6.2, pandas_to_vertica create a temp table. To store it permanently, use the 'to_db' method.
```python
cluster_vdf.to_db(name = 'stocks_interday_cluster',
                             schema = 'public',
                             relation_type = 'table',
                             inplace = True)
```

**Comment by liv4unix** [comment]
My sincere apologies, I forgot to include the version:

version()
[10, 1, 0, 3]
