### ISSUE TITLE
model.plot(ax= ??) syntax to overcome "Clustering Plots are only available in 2D or 3D" Exception

### ISSUE THREAD

**Issue by liv4unix** [vertica/VerticaPy#136]
The "ax" option syntax does not appear to align with traditional matplotlib ax.plot syntax for plotting 2D/3D variables from a multidimensional model.  

Example:

#Kmeans model that uses all 8 columns are the predictors:

kmeans_model.fit("stocks_interday")

#I cannot figure out how to plot just 2 predictors (Ie., "volume" [x] and "ticker" [y]) using the 'ax' option - every method that I have tried fails. 

kmeans_model.plot()

Has the 'ax' option been tested and verified to work for a multidimensional design?  If so, can I get the proper syntax?

Thanks!
Theresa

**Comment by oualib** [comment]
The 'plot' methods of models is limited for something more extended, you can:
 - add the prediction to a vDataFrame using the 'predict' method
 - draw the scatter plot using scatter
In sklearn, there is no 'plot' method for the models. Besides to draw more than 3 dimensions, the only way is to draw a PCA plot. It will be added in 0.6.3 and it can be done by creating afterwards a PCA model and drawing the components.

**Comment by liv4unix** [comment]
Ah, okay, thank you for this!
