### ISSUE TITLE
How to display limited dataset 

### ISSUE THREAD

**Issue by raviguptag** [vertica/VerticaPy#142]
from verticapy.datasets import load_commodities
import verticapy.stats as st
commodities = load_commodities()
commodities.set_display_parameters(rows = 5)

Error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-4666dfc1888d> in <module>
----> 1 commodities.set_display_parameters(rows = 5)

AttributeError: 'vDataFrame' object has no attribute 'set_display_parameters'
-------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/1329547/123946897-556a2c80-d9bd-11eb-98aa-99148caba2d6.png)

**Comment by oualib** [comment]
Hi Ravi,

set_display_parameters is deprecated.

Please check this function:
https://www.vertica.com/python/documentation_last/utilities/set_option/index.php

Use param max_rows:
set_option('max_rows', 5)
