### ISSUE TITLE
Random state doesn't work in version 0.6.1

### ISSUE THREAD

**Issue by balleem** [vertica/VerticaPy#143]
Hello,

It seems that random_state doesn’t work in version 0.6.1. It worked in version 0.5 but in the most recent version, using random_state in models doesn't seem to have any effect.
For example, for train_test_split:

base = load_titanic()
train,test = base.train_test_split(order_by = ["name"], test_size = 0.3, random_state=42)
train.shape()
test.shape()

If I run this section twice, I get different results for train and test shapes, which is not the case when I use version 0.5.

Could you have a look at this ?

Thanks

**Comment by oualib** [comment]
Hi @balleem ,

Indeed, it is corrected and it will be available for v0.7.0.
We will add a more robust UT to avoid these kind of issues.

Badr
