### ISSUE TITLE
converting models to C++ 'to_cpp'

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#144]

**Comment by iamdionysus** [comment]
This will be really great! When the machine learning model is well trained and ready to be in production, the production model has a good chance to have its model converted in C++ or something for various reason.

**Comment by oualib** [comment]
Unfortunately, this functionality is not really feasible at the moment because of many reasons:
 - Hard to test the perf and accuracy of the output model.
 - Not enough traction to prioritise it.
We can reopen or create a new issue later if needed.
