### ISSUE TITLE
vDataFrame.to_db method has relation_type="insert" parameter, does COMMIT follow through?

### ISSUE THREAD

**Issue by iamdionysus** [vertica/VerticaPy#149]
I see that I can use to_db to insert as discussed in https://github.com/vertica/VerticaPy/issues/115. But I found that it does not COMMIT. Shouldn't it be followed through if the relation_type="insert"?

**Comment by oualib** [comment]
Indeed, it was added and it will be rectified in v0.7.0. Thanks for noticing it.
