### ISSUE TITLE
How to browse all available methods in online documentation

### ISSUE THREAD

**Issue by IzakMarais** [vertica/VerticaPy#155]
How do I browse a list of all available methods online documentation (eg. list all the methods on [vDataFrame](https://www.vertica.com/python/documentation_last/vdataframe/) )?

I think I managed to navigate to such a list in the past via the search bar, but I cannot find again.

**Comment by oualib** [comment]
Hi Izak, you mean all the methods in one single file?

**Comment by IzakMarais** [comment]
Yes, an html list of methods available on an object, with links to the current help pages. 

E.g. the current [to_db page](https://www.vertica.com/python/documentation_last/vdataframe/main-methods/to_db/) has the following navigational aid in the top right: 
![image](https://user-images.githubusercontent.com/8266640/129366974-8a1651fd-6c1f-433f-a6b8-97138476a403.png)

I would want to click on `Main Methods` and just see an html list of links to all the methods on vDataFrame.

**Comment by oualib** [comment]
Hi @IzakMarais,
It is now available: 
https://www.vertica.com/python/documentation_last/vdataframe/index.php

**Comment by IzakMarais** [comment]
That looks perfect, thanks.
