### ISSUE TITLE
Problem spearman

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#163]
Hello,

I calculated spearman correlation in titanic database with corr function in verticapy and pandas. 
My results are different. In verticapy, as in documentation : 
![image](https://user-images.githubusercontent.com/49387599/131519934-a01ef3f3-6b6a-4a8f-a876-1c251ba881e5.png)

In pandas : 
![image](https://user-images.githubusercontent.com/49387599/131520110-06d62bf0-da2d-43fb-a81b-7dfdfaf1e708.png)

Are you sure that your spearman correlation is ok?

**Comment by oualib** [comment]
Hi Alexandre,

spearman correlation is the Pearson correlation of the ranks. You can look at the SQL code generation to see that the query matches with the definition. Besides, if you take features with duplicates, the results might differ as it will not be deterministic.

Badr
