### ISSUE TITLE
question regr -> sxx

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#164]
Hello, 

I have a question on regr function. With titanic data and the script below : 

![image](https://user-images.githubusercontent.com/49387599/132011942-9f51e531-5691-4765-9aef-5bce8ed33675.png)

We see that we have a float value for "survived". But, with the description in verticapy documentation, we calculate the "sum of squares of survived". Survived being int, how can we have float value? 

I have the same question with sxy and syy parameters.

**Comment by oualib** [comment]
Hi Alexandre,

The function is using: REGR_SXX aggregation. If you look at the Vertica doc:
https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Aggregate/REGR_SXX.htm
The definition is the same. But it seems to not be precise. If you want a correct answer, look at this link:
https://math.stackexchange.com/questions/1499752/sxx-in-linear-regression

As the average is used in the computation, you will probably get a float.

Badr

**Comment by oualib** [comment]
@ansleis, can you please take a look at this to be more precise on our official Vertica doc?

**Comment by oualib** [comment]
The next documentation will include a more precise definition.
