### ISSUE TITLE
Remove left trailing spaces from pandas and csv

### ISSUE THREAD

**Issue by antoinemertz** [vertica/VerticaPy#168]
Hi,

I've noticed a behavior from the function `pandas_to_vertica` (and I think also from the function `read_csv` because `pandas_to_vertica` uses this function to ingest the data in Vertica). When I want to ingest a column with text data in it, it will remove left trailing spaces (not right ones). How can I keep this spaces at the beginning of the text?

```
>>> import pandas as pd
>>> from verticapy import *
>>> from verticapy.utilities import *
>>> df = pd.DataFrame({"id": [0,1,2,3,4,5,6,7,8,9], "name": ["Manu", " Hugo", "Nath ", " Vincent ", " Nadege", " Leo ", " Julien    ", "   Corentin", " Alexandre ", "Falvie     "]})
>>> df["name"].unique() # this show me the correct text with trailing spaces
array(['Manu', ' Hugo', 'Nath ', ' Vincent ', ' Nadege', ' Leo ',
       ' Julien    ', '   Corentin', ' Alexandre ', 'Falvie     '],
      dtype=object)
>>> pandas_to_vertica(df = df, name = table_name, schema = schema, cursor = cursor)
>>> vdf = vDataFrame("{}.{}".format(schema, table_name), cursor)
>>> vdf["Name"].distinct()
['Alexandre ',
 'Corentin',
 'Falvie     ',
 'Hugo',
 'Julien    ',
 'Leo ',
 'Manu',
 'Nadege',
 'Nath ',
 'Vincent ']
```

As you can see in the example, left trailing spaces are removed using `pandas_to_vertica`.
I'm currently using VerticaPy version 0.5.0, maybe it is fixed in higher version and we will soon upgrade VerticaPy version in our use cases.

Thank you in advance for your help,

Antoine

**Comment by oualib** [comment]
Hi Antoine,

Indeed, it is when creating the pandas CSV file that it happens. We just need to add the csv.QUOTE_ALL in the function's parameters. It will be solved in v0.7.1.

Thanks a lot for your contribution,

Badr
