### ISSUE TITLE
Using username in flex table names breaks if not valid table name

### ISSUE THREAD

**Issue by taturl** [vertica/VerticaPy#186]
https://github.com/vertica/VerticaPy/blob/8ef00f7c8e049400ae30adc26fea9b96c53a0122/verticapy/utilities.py#L587

If username includes characters like "-", creating flex table with username in its name fails.

Suggestion:
```
flex_name = "VERTICAPY_{}_FLEX".format(get_session(cursor, add_username = False))
```
Or proper sanitization.

Thanks!

**Comment by oualib** [comment]
Thanks a lot. It will be corrected in the next PR.
