### ISSUE TITLE
Error with pivot_table_chi2 

### ISSUE THREAD

**Issue by corentinlelannier** [vertica/VerticaPy#194]
Hello,

I think there is a mistake in the calculation of the chi2 in the pivot_table_chi2 function.

For exemple, in the documentation, the chi2 statistic between the variable "Sex" and "Survived" returned is 38.3735130215037.
When we try with the function chi2_contingency, in the scipy package, we get 345.12775126385327 without the Yates correction,
 342.81285537487196 with the correction.

When I was looking for the formula, i found this :

```
all_chi2 = []
for row in tmp_res:
    L = [int(x) if x != '' else 0 for x in row]
    n = sum(L)
    expected = n / len(L)
    all_chi2 += [np.sqrt((x - expected) ** 2 / expected) for x in L]
chi2_list += [(col, sum(all_chi2), vdf[col].distinct(), self[col].isnum())]
```
The closest formula for the chi2 was the one bellow, but the "expected" values would be incorrect : 
![image](https://user-images.githubusercontent.com/43996984/146776778-388bd8f5-f223-4203-9459-616ef605a229.png)

With the following code, i get the same thing as scipy by using the equivalent formula : 
![image](https://user-images.githubusercontent.com/43996984/146777295-2e507637-2926-42cd-8c82-26c4f7540846.png)

```
i = 0
all_chi2 = []
for row in tmp_res:
    j=0
    for col_in_row in row:
        all_chi2 += [(col_in_row) ** 2 / (rowsums[i]*colsums[j])]
        j += 1
    i += 1
sum(sum(tmp_res))*(sum(all_chi2)-1)
```

With this formula, we get the same result as scipy without the correction, but we never get the verticapy result with scipy.

Could you have a look at this ?

Regards 

**Corentin**

**Comment by oualib** [comment]
Hi @corentinlelannier,

Can you please tell me if this example is correct: https://www.analyticsvidhya.com/blog/2021/05/implement-of-decision-tree-using-chaid/ ?

I tried to reproduce it and I got the exact same results.

Besides, I don't know if we are computing the same things in the scipy.chi2_contingency as in the function, we are not considering a response column.

Badr

**Comment by corentinlelannier** [comment]
Hello @oualib ,

We compared the CHAID algo with different ones and we didn't get the same result.
I don't understand why there is a square root in the calculus of the chi2 in your link, I don't find it anywhere else. 

Morevover, it seems your algorithm can't merge two class. 
We found this algorithm that may help you : https://rdrr.io/rforge/CHAID/man/chaid.html

Corentin

**Comment by oualib** [comment]
Hi @corentinlelannier,

Thanks for your piece of code. We can correct the 'pivot_table_chi2' in the next release.
For CHAID, what do you mean "merging two classes"? Do you mean merging two categories?

Thanks again for your collaboration,

**Comment by corentinlelannier** [comment]
Yes, I meant merging two categories.

Your welcome,
Regards

**Comment by oualib** [comment]
The main issue is corrected. The chi2 is now correctly computed using the formula you proposed. Thanks a lot for your help. You can create another issue to propose an improvement on the CHAID trees (merging categories together) and explaining how we should proceed.
