### ISSUE TITLE
pandas_to_vertica() & to_csv() issues

### ISSUE THREAD

**Issue by jjfrasca** [vertica/VerticaPy#195]
I have two questions related to the verticapy library. Could you help me with them?

1.	I’m having issues storing pandas dataframes directly into vertica using the pandas_to_vertica function [[vertica.com](https://www.vertica.com/python/documentation_last/utilities/pandas_to_vertica/)]. I get the following error ‘FileNotFoundError: [WinError 2] The system cannot find the file specified: MY FILE NAME’, or I get the following error:

![image](https://user-images.githubusercontent.com/67272234/147661257-c8d512c6-a52b-4d1b-ae0c-7f276f8503f4.png)

2.	As a workaround I instead save the pandas dataframe as a .csv file and store it to vertica using the read_csv function [[vertica.com](https://www.vertica.com/python/documentation_last/vdataframe/main-methods/to_csv/)]. However there may be some data formatting/data loss issues as I’m noticing around 0.07% of rows seem to not successfully store in vertica on a table I am working with.

![image](https://user-images.githubusercontent.com/67272234/147661248-ea2345be-e117-4d0a-a597-1ef432205c13.png)

I contacted the Vertica Support Team but they were not able to figure out why this was happening. They instructed me to post on the github.

Anyone have any suggestions?
Thank you!

**Comment by oualib** [comment]
Hi,

The function is creating a temp csv file in the client side. This function will change in the next release. It will use multiple insertions instead. The number of rows to ingest will be defined by the user.

Your workaround can work well but be careful on the string quotes and the delimiter. The lines you are not ingesting might be not formatted well (strings with multiple quotes for example).

Badr

**Comment by oualib** [comment]
Hi,

The function is creating a temp csv file in the client side. In the next PR, you will be able to indicate the location of this file.
Some rows may not be ingested because of the usage of some special characters. The new function "pandas_to_vertica" takes care of this.

Badr

**Comment by jjfrasca** [comment]
Thanks Badr! Will check it out.
