### ISSUE TITLE
Implementing TF-IDF

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#196]
In information retrieval, tf–idf (also TF*IDF, TFIDF, TF-IDF, or Tf-idf), short for term frequency–inverse document frequency, is a numerical statistic that is intended to reflect how important a word is to a document in a collection or corpus. It is often used as a weighting factor in searches of information retrieval, text mining, and user modeling. The tf–idf value increases proportionally to the number of times a word appears in the document and is offset by the number of documents in the corpus that contain the word, which helps to adjust for the fact that some words appear more frequently in general. tf–idf is one of the most popular term-weighting schemes today. A survey conducted in 2015 showed that 83% of text-based recommender systems in digital libraries use tf–idf.

**Comment by PriyankaMF** [comment]
@oualib do we need to have a server side issue on this? If yes, can you please raise and let me know so I can track.

**Comment by oualib** [comment]
@mat-shyR any news on this?

**Comment by oualib** [comment]
@mat-shyR is currently implementing it. It will be available soon.
