### ISSUE TITLE
pandas_to_vertica, temporary table

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#197]
hello,

I think there is a problem with pandas_to_vertica function. In fact, I can't save a pandas dataframe in vertica with this function. I think, it always creates temporary tables. In source code, we are (lines 522-525) : 

        if not(tmp_name):
            vdf = read_csv(path, cursor, table_name=tmp_name, temporary_local_table=True, parse_n_lines=parse_n_lines,)
        else:
            vdf = read_csv(path, cursor, table_name=tmp_name, schema=schema, temporary_local_table=False, parse_n_lines=parse_n_lines,)

where not(tmp_name) =  True if name <> "".
In documentation, we are for "name" variable : "If empty, a temporary local table is created". So, if "name" isn't empty, and not(tmp_name) =  True we want a table and not temporary table. In code, we are temporary_local_table=True line 523, but we want temporary_local_table=False. I think you inversed lines 523 and 525.  

Regards

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Thanks a lot for reporting the issue.
It will be corrected in the next PR.

Badr
