### ISSUE TITLE
KeyError: 'ODBCINI'

### ISSUE THREAD

**Issue by meatcomputer** [vertica/VerticaPy#198]
It seems verticapy can't find the ODBCINI system variable. The package was installed from pip in a venv from pycharm. 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [8], in <module>
----> 1 read_dsn("VERTICAP")

File c:\tools\miniconda3\lib\site-packages\verticapy\connect.py:250, in read_dsn(section, dsn)
    248 confparser.optionxform = str
    249 if not dsn:
--> 250     dsn = os.environ["ODBCINI"]
    251 confparser.read(dsn)
    252 if confparser.has_section(section):

File c:\tools\miniconda3\lib\os.py:679, in _Environ.__getitem__(self, key)
    676     value = self._data[self.encodekey(key)]
    677 except KeyError:
    678     # raise KeyError with the original key value
--> 679     raise KeyError(key) from None
    680 return self.decodevalue(value)

KeyError: 'ODBCINI'

**Comment by oualib** [comment]
Hi,

VerticaPy only tries to access the os.environ directory. It seems that you did not correctly set your environment variable.

To look at the environment variables available, you can run the following command:
```python
import os
os.environ
```

Badr
