### ISSUE TITLE
asfreq, bfill, ffill

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#199]
Hello, 

I use smart meters dataset and I use this code : 

```
#calcul du bfill sur id = 4
smart_meters_freq_bfill = smart_meters_copy.search("id = 4").asfreq(ts = "time",
          rule = "1 hour",
          method = {"val": "bfill"},
          by = ["id"])

#calcul du ffill sur id = 4
smart_meters_freq_ffill = smart_meters_copy.search("id = 4").asfreq(ts = "time",
          rule = "1 hour",
          method = {"val": "ffill"},
          by = ["id"]) 
```

resultats are : 

![image](https://user-images.githubusercontent.com/49387599/152942397-7362b727-c247-49b2-8dbc-3f24767ea4d4.png)

We can see that bfill and ffill have the same performance. 

The ffill's performance is ok, but  the bfill's performance isn't ok. 

Regards 

Alexandre

**Comment by oualib** [comment]
Hi Alexandr,

I did not understand the request?
Can you provide more information?

Thanks,

Badr

**Comment by lepelletieralexandre** [comment]
Hello,

In this example, we have 2 times with 2 values : 
![image](https://user-images.githubusercontent.com/49387599/155688343-ef7e15e5-ae73-47bf-8d80-a601137002f4.png)

For ffill, for all times between 07:45 and 13:00, we should have the value 0.102 (it's ok). But for bfill, we should have the value 0.622 and we have the value 0.102,

So, method = {"val": "bfill"} is wrong.

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Thanks for reporting this. I don't understand why the function is acting this way. It is using Vertica built-in functions TS_FIRST_VALUE and TS_LAST_VALUE.
@afard can you please look at this?

**Comment by oualib** [comment]
I found the reason. When using this function, Vertica will cut the TS into multiple intervals of size 'rule'. The propagation and interpolation will happen in the interval. In your case, the interval always include 1 value, so the 3 interpolations will be the same. We have to improve the documentation to explain more precisely the function.

**Comment by afard** [comment]
Assigning back to you Badr as you discovered that it is a documentation issue.

**Comment by lepelletieralexandre** [comment]
It's not a documentation problem. 

ffill is forward propagation. So, all intervals between 7:45 and 13:00 must have the value 0.102. But bfill is backward propagation, so all interval between 7:45 and 13:00 must have the value 0.622. ffill and bfill function.

they are exemples on these links : 
 ffill : https://www.geeksforgeeks.org/python-pandas-dataframe-ffill/
bfill : https://www.geeksforgeeks.org/python-pandas-dataframe-bfill/

**Comment by oualib** [comment]
Alexandre,
It's a bfill on the time slice. Look at the doc of "TS_LAST_VALUE": https://www.vertica.com/docs/11.1.x/HTML/Content/Authoring/SQLReferenceManual/Functions/TimeSeries/TS_LAST_VALUE.htm
I know it can be seen as a weird behavior but we can not do anything on the VerticaPy side at the moment. We will need to implement it at the Vertica side.

**Comment by oualib** [comment]
I just create a Jira to have a proper Back Filling function. So I'll close this issue and see internally what we can do.
