### ISSUE TITLE
case when 

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#200]
Hello,

I use titanic dataset and this code :  

```
titanic_copy.case_when("age_category",
                  titanic_copy["age"] > 60 , "seniors",
                  titanic_copy["age"] < 25 and titanic_copy["age"] >= 18, "young adults",
                  titanic_copy["age"] < 18 and titanic_copy["age"] >= 12, "teenagers",
                  titanic_copy["age"] < 12, "children",
                  "adults")
titanic_copy[["age", "age_category"]].search("age = 30 ")
```

the result is : 

![image](https://user-images.githubusercontent.com/49387599/152943300-b0b3b708-009e-4159-b04d-6a2c9f255ff0.png)

for age = 30, we should have adults, not yound adults. When we use "or" or "and", "case when" seems to use the last condition only. 

Regards

Alexandre

**Comment by oualib** [comment]
Hi Alexandr,

The "and" operator can not be modified, it's intrinsic to Python. The magic operator to represent the "and" is "&".

```python
titanic_copy.case_when("age_category",
                       titanic_copy["age"] > 60 , "seniors",
                       (titanic_copy["age"] < 25) & (titanic_copy["age"] >= 18), "young adults",
                       (titanic_copy["age"] < 18) & (titanic_copy["age"] >= 12), "teenagers",
                       titanic_copy["age"] < 12, "children",
                       "adults")
```

Do not forget the parenthesis also.
```python
titanic_copy["age"] < 18 & titanic_copy["age"] >= 12
```
will not work.

Best,

Badr

**Comment by lepelletieralexandre** [comment]
Hello, 

Thanks, it's work with "&". 
But when we use "and" or "or", the function doesn't return error and the result is wrong. Can you add a condition which return an error if we use "and" or "or"? Many fonctions use SQL code in Verticapy, with the words "and" and "or", and it's easy to be wrong.

Alexandre

**Comment by oualib** [comment]
Unfortunately, "and" and "or" are protected by Python. We can not have any action on them. I know it would much more pleasant to use those operators but there is nothing we can do...
