### ISSUE TITLE
discretize, same_freq

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#201]
Hello,

I use titanic dataset and this code : 

```
titanic_copy = titanic_copy.search("age is not null")
titanic_copy["age"].discretize(method = "same_freq", bins = 5)
display(titanic_copy["age"])
titanic_copy["age"].hist()
```

the result is : 
![image](https://user-images.githubusercontent.com/49387599/152945306-abf289fc-4df4-479f-8c91-4cd634c13b66.png)

I have 5 class (5 bins) but the last class is smaller than the others. what?

I use the same dataset keeping NULL values : 

```
titanic_copy2["age"].discretize(method = "same_freq", bins = 5)
display(titanic_copy2["age"])
titanic_copy2["age"].hist()
```

but the result is the same : 

![image](https://user-images.githubusercontent.com/49387599/152945748-60c44e98-7bb5-4484-865a-35d716fec735.png)

Regards,

Alexandre

**Comment by oualib** [comment]
This issue is corrected. Thanks again for reporting it.
