### ISSUE TITLE
gen_dataset

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#202]
Hello,

I can't gen dataset like the exemple in the doc : https://www.vertica.com/python/documentation_last/datasets/gen_dataset/index.php

i use this code : 

```
from verticapy.datasets import gen_dataset
import datetime

gen_dataset(features_ranges = {"name": {"type": str, "values": ["Badr", "Badr", "Raghu", "Waqas",]},
                               "age": {"type": int, "range": [20, 40]},
                               "distance": {"type": float, "range": [1000, 4000]},
                               "date": {"type": datetime.date, "range": ["1993-11-03", 365]},
                               "datetime": {"type": datetime.datetime, "range": ["1993-11-03", 365]},}, cursor = cur,) 
```

I have this error : 

![image](https://user-images.githubusercontent.com/49387599/152947830-b62855bb-9975-4d16-972e-881ae8b79264.png)

What is the problem? 

Regards 

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

You need to have Vertica 9.3 to be able to use this function. We will try to find a solution to send a proper error message.

Best,

Badr
