### ISSUE TITLE
edit_distance

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#203]
Hello, 

i use the exemple of edit_distance https://www.vertica.com/python/documentation_last/stats/edit_distance/index.php : 
```
import verticapy.stats as st
df = tablesample({"x": ['hello', 'apple', 'heroes', 'allo']}).to_vdf()

df["edit_distance_x"] = st.edit_distance(df["x"], 'heyllow')
```

i have this error : 
![image](https://user-images.githubusercontent.com/49387599/152948951-332dd807-286e-483a-8575-c3c235cf0de5.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

You need to have Vertica 10.1 to be able to use this function. We will try to find a solution to send a proper error message.

Best,

Badr
