### ISSUE TITLE
soundex

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#204]
Hello,

i use the exemple of soundex https://www.vertica.com/python/documentation_last/stats/soundex/index.php :

```
import verticapy.stats as st
df = tablesample({"x": ['hello', 'apple', 'heroes', 'allo']}).to_vdf()

df["soundex_x"] = st.soundex(df["x"],)
```

i have this error :

![image](https://user-images.githubusercontent.com/49387599/152949453-89e5e1ac-2271-4026-a43a-3ea15a0d83a5.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

You need to have Vertica 10.1 to be able to use this function. We will try to find a solution to send a proper error message.

Best,

Badr
