### ISSUE TITLE
soundex_matches

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#205]
Hello,

I use the exemple of soundex_matches https://www.vertica.com/python/documentation_last/stats/soundex_matches/index.php :

```
import verticapy.stats as st
df = tablesample({"x": ['hello', 'apple', 'heroes', 'allo']}).to_vdf()

df["soundex_matches_x"] = st.soundex_matches(df["x"], "heyllow")
```

I have this error :

![image](https://user-images.githubusercontent.com/49387599/152949666-f347d3d1-55de-4abc-8b72-20d522aa77fc.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

You need to have Vertica 10.1 to be able to use this function. We will try to find a solution to send a proper error message.

Best,

Badr
