### ISSUE TITLE
ljungbox

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#207]
Hello,

There a problem with ljungbox function. your calcul begin with a lag 0, but in this doc : https://en.wikipedia.org/wiki/Ljung%E2%80%93Box_test the calcul begin with a lag 1! 

I compare your result with amazon dataset : 

```
from verticapy.stats import ljungbox
vpy_jun = ljungbox(amazon_unique_copy,
         column = "random",
         ts = "date",
         p = 10,
         alpha = 0.05,
         box_pierce = False)
```
the result is : 
![image](https://user-images.githubusercontent.com/49387599/152965238-475246a6-d4a8-432c-95dc-8b649f0caab0.png)

In python : 

`statsmodels.stats.diagnostic.acorr_ljungbox(amazon_unique_copy.to_pandas().sort_values("date")["random"], lags = 10, auto_lag = False)`

the result is : 

![image](https://user-images.githubusercontent.com/49387599/152965361-52d65e7e-dccb-41d9-9cf9-4181acce2b47.png)

The big difference is the lag 0 which is not present is python. 
Event if you remove the lag 0, there will be an other small difference, but it will be an other issue. 

Regards,

Alexandre

**Comment by oualib** [comment]
This issue is corrected. Thanks again for reporting it.
