### ISSUE TITLE
mkt

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#208]
Hello,

There is a problem when you calcul STDS. In source code, you use : 

`SELECT row FROM (SELECT ROW_NUMBER() OVER (PARTITION BY NUMBER) AS row FROM DTDSWSP310.amazon2) VERTICAPY_SUBTABLE GROUP BY row`

But you must use : 

`SELECT MAX(row) FROM (SELECT ROW_NUMBER() OVER (PARTITION BY NUMBER) AS row , NUMBER FROM DTDSWSP310.amazon2) VERTICAPY_SUBTABLE GROUP BY NUMBER`

Regards

Alexandre

**Comment by oualib** [comment]
This issue is corrected. Thanks again for reporting it.
