### ISSUE TITLE
enet_search_cv

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#209]
Hello,

This issue will be long. There are 2 problems. 

First : 

This function don't run if the vdataframe have been modified. The problem is "shema_relation" function in bayesian_search_cv function. 
![image](https://user-images.githubusercontent.com/49387599/152967714-8292312e-528f-43ee-b0eb-3318588af573.png)

so when I run : 

`enet_search_cv(input_relation = titanic, 
               X = ["age", "fare", "pclass",], 
               y = "survived", 
               metric = "auto",
               cv = 3, 
               estimator_type = "enet",
               cutoff = -1,
               cursor=cur,
               print_info = True,)`

I have : 
![image](https://user-images.githubusercontent.com/49387599/152967799-5de87d0e-e26e-4428-b124-ccc469c37f7c.png)

If the vdataframe haven't been modified : 
![image](https://user-images.githubusercontent.com/49387599/152967933-4275c9ae-98a4-45b6-a8a3-4c23c9ef7847.png)
 it's ok.

Second problem : 

When enet_search_cv use bayesian_search_cv, the prameter "prams_gs" is empty. 

To show the problem rapidly, when we are : 
![image](https://user-images.githubusercontent.com/49387599/152969033-ad4b986c-8855-41cd-b340-b17a6655a2f2.png)

and we use : 

![image](https://user-images.githubusercontent.com/49387599/152969137-54b5c9c8-ac06-4c62-a33a-f09b6a13d185.png)

I think it's because we haven't access to public shema : 

![image](https://user-images.githubusercontent.com/49387599/152969546-eefdf28e-ca9e-4ffb-a86d-efdf16839f5a.png)

So, when we create "estimator" variable in enet_search_cv, we must give a shema parameter to solve it. 

Regards,

Alexandre

**Comment by oualib** [comment]
Thanks a lot Alexandre.
This problem will be solved in the next PR thanks to the "set_option" function.
