### ISSUE TITLE
DBSCAN

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#210]
Hello,

When I use 2 times DBSCAN function, I have 2 differents results. 
For exemple, with iris dataset : 
![image](https://user-images.githubusercontent.com/49387599/152985713-124cfc49-5c1c-4b4d-bbb9-a8e82404fdb9.png)

The algorithme on this link https://fr.wikipedia.org/wiki/DBSCAN show that the results must be the same at each time. 

I think that you stop the iteration too early. You don't search all neighbors for each cluster.

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

By looking at wikipedia page (https://en.wikipedia.org/wiki/DBSCAN) on the section: Disadvantages. They emphasize on the fact that DBSCAN is not deterministic: "DBSCAN is not entirely deterministic: border points that are reachable from more than one cluster can be part of either cluster, depending on the order the data are processed. For most data sets and domains, this situation does not arise often and has little impact on the clustering result."

Maybe, you can create another issue to seed the randomness of the algorithm.

Badr
