### ISSUE TITLE
CountVectorizer, attribute get_attr

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#212]
Hello,

The attribute "get_attr" doesn't work. 
With titanic dataset, when I use : 
```
drop(schema + ".CountVectorizer_titanic",cur,method = "text")
model = CountVectorizer(name = schema + ".CountVectorizer_titanic", cursor = cur,
                lowercase = True,
                max_df = 1.0,
                min_df = 0.0,
                max_features = -1,
                ignore_special = True,
                max_text_size = 2000)
model.fit(schema + ".titanic2", ["name"])
model.get_attr(attr_name = "")
```

I have the error : 
![image](https://user-images.githubusercontent.com/49387599/152989591-edb8b9cc-37ab-4af0-a556-c110c88cf15d.png)

I think is because "model" isn't a model, but a text. When I wan't drop the model, I must use : 

`drop(schema + ".CountVectorizer_titanic",cur,method = "text")`

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Thank you for reporting this bug. It will be corrected in the next release.
You can still use:
```
model.drop()
```
To drop it.

Badr

**Comment by oualib** [comment]
This issue is corrected. Thanks again for reporting it.
