### ISSUE TITLE
SVD, method inverse transform

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#213]
Hello, 

With iris dataset, I have this problem : 

![image](https://user-images.githubusercontent.com/49387599/152993058-309da79d-d4a9-4dd8-aa07-491303b37d1b.png)

I don't know why this method doesn't work

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

To use the 'inverse_transform', you should use as input a relation or a vDF. What are you trying to transform?
The function does not need "mandatory parameters" because of some specific use-cases.

Badr

**Comment by lepelletieralexandre** [comment]
Hello,

I tested and it works, thank. So, the problem is the documentation : https://www.vertica.com/python/documentation_last/learn/Model/inverse_transform/
You give an example where the paremeters vdf and X are empty and in the documentation, these parameters are optionals (but they aren't). 

Can you improve the documentation? 

Alexandre
