### ISSUE TITLE
PCA, inverse transform method

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#214]
Hello, 

With iris dataset, I have this problem : 

![image](https://user-images.githubusercontent.com/49387599/152993247-1860e8d9-073f-44f5-9f76-36a0690e0bb8.png)

I don't know why this method doesn't work

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

To use the 'inverse_transform', you should use as input a relation or a vDF. What are you trying to transform?
The function does not need "mandatory parameters" because of some specific use-cases.

Badr
