### ISSUE TITLE
MCA

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#215]
Hello,

There are 3 problems.

first : With iris dataset, I have this problem :

![image](https://user-images.githubusercontent.com/49387599/152993465-7d3180d4-fd63-4851-8a84-236a0a55adba.png)

I don't know why this method doesn't work.

Second : The method to_sklearn doesn't work. It's normal, MCA doesn't exist in sklearn. 

thirds : problem with to_sql method : 

![image](https://user-images.githubusercontent.com/49387599/152993799-917d5d39-9c9b-4442-9b03-5ea7d577edc9.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

1. It is normal, we need to update the doc on inverse_transform
2. The 'to_sklearn' is not available for this type of models AND this function is deprecated. memModels are much more portable and easy to use.
3. memModels are not yet available for MCA.

If you need to export MCA to memModel, please create a new issue to ask for this feature.

I'll transform this issue to a "doc" issue.

Badr
