### ISSUE TITLE
classification report

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#216]
Hello, 

2 problems in classification report. 

with titanic dataset and logistic regression like this : 

```
from verticapy.learn.linear_model import LogisticRegression
drop(schema + ".rl_titanic", cursor = cur, method = "model")
model = LogisticRegression(name = schema + ".rl_titanic",
                   penalty = 'None',
                   tol = 1e-4,
                   C = 1.0,
                   max_iter = 100, 
                   solver = 'Newton',
                   l1_ratio = 0.5)
model.fit(titanic_copy, ["fare", "age"], "survived")
model.predict(titanic_copy, ["fare", "age"], "survived_pred")
titanic_copy.eval("survived_pred2", "case when survived_pred <= 0.5 then 0 when survived_pred > 0.5 then 1 end")
titanic_copy = titanic_copy.sort({"col_id" : "asc"})
```
classification report result is : 

![image](https://user-images.githubusercontent.com/49387599/152996313-0dc56374-dd52-4ca4-b053-ca0bc3202e3e.png)

the problems are f1_score and cutoff. 

With this code in python : 

```
#calcul du f1 score et cutoff en py
import sklearn as sk
df_titanic = titanic_copy.to_pandas()
df_titanic = df_titanic.loc[(df_titanic["fare"].notna()) & (df_titanic["age"].notna())]
py_class_report = pd.DataFrame([[0] for i in range(2)], 
            index = [ "f1_score", "cutoff"],
            columns = ["value"])

py_class_report.loc["f1_score"] = np.round(sk.metrics.f1_score(df_titanic["survived"], df_titanic["survived_pred2"]),10)

fpr, tpr, thresholds = sk.metrics.roc_curve(df_titanic["survived"], df_titanic["survived_pred"])
optimal_idx = np.argmax(tpr - fpr)
py_class_report.loc["cutoff"] = thresholds[optimal_idx]
```

I have : 

![image](https://user-images.githubusercontent.com/49387599/152996520-d1bb01e3-f96c-41c3-a4c0-2781d94ddc62.png)

for f1_score, with the code : 

```
from verticapy.learn.metrics import f1_score
f1_score("survived", "survived_pred2", titanic_copy)
```

I have the same result that python. In classification report, you inverse tnr and ppv in the formula. 

for cutoff, in verticapy, you use : 

```
from verticapy.learn.model_selection import roc_curve
roc_curve("survived", "survived_pred2", titanic_copy, nbins = 30, best_threshold = True)
```

that return 0.9666667. But with : 

`roc_curve("survived", "survived_pred", titanic_copy, nbins = 1000, best_threshold = True)`

we have 0.36, like python. 

We must increase the parameter bins to have the good result, but we can't change this parameter in classification report function.

Regards 

Alexandre

**Comment by oualib** [comment]
Thanks a lot Alexandre, 
It will be corrected in the next PR.
