### ISSUE TITLE
anova_table

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#218]
Hello,

When you calcul the number of lines, you keep the lines where prediction is null. 

Exemple with titanic dataset : 

![image](https://user-images.githubusercontent.com/49387599/153000498-7e0e1405-c52a-4d32-b9ed-43946860a21e.png)

You musn't keep the null prediction when you calcul number of lines. 

regards,

Alexandre

**Comment by oualib** [comment]
Thanks Alexandre, 
It was corrected in the last PR.
