### ISSUE TITLE
r2_score ajusté

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#220]
Hello,

When you use r2_score function with k = 2, you keep null prediction to calcul the number of lines, but you must remove null prediction to do that. 

with titanic exemple : 

![image](https://user-images.githubusercontent.com/49387599/153001808-962936b5-70cd-4364-b7af-ab7d323378f4.png)

regards,

Alexandre

**Comment by oualib** [comment]
This issue is corrected. Thanks again for reporting it.
