### ISSUE TITLE
problem contour plot, DummyTreeClassifier, DecisionTreeClassifier, DummyTreeRegressor, NaiveBayes

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#222]
Hello,

We are a problem with contour_plot method on DummyTreeClassifier, DecisionTreeClassifier, DummyTreeRegressor, NaiveBayes function. 

let's take DummyTreeRegressor and iris dataset as an example : 

`drop(name = schema +".model_iris_test2", cursor = cur, method = "model")
model = DummyTreeRegressor(name = schema +".model_iris_test2", cursor = cur)
model.fit(iris,["SepalLengthCm","PetalWidthCm"], "PetalLengthCm")`

when we use contour : 

![image](https://user-images.githubusercontent.com/49387599/153004955-3a96029c-fb33-4031-90ee-1032f57f4829.png)

When we search the problem, we take contour_plot function, and we truncate this function : 

```
def contour_plot(
    vdf,
    columns: list,
    func,
    nbins: int = 100,
    cbar_title: str = "",
    pos_label: Union[int, str, float] = None,
    ax=None,
    **style_kwds,
):
    if not(cbar_title) and str(type(func)) in ("<class 'function'>", "<class 'method'>",):
        cbar_title = func.__name__
    all_agg = vdf.agg(["min", "max"], columns)
    min_x, min_y = all_agg["min"]
    max_x, max_y = all_agg["max"]
    if str(type(func)) in ("<class 'function'>", "<class 'method'>",):
        xlist = np.linspace(min_x, max_x, nbins)
        ylist = np.linspace(min_y, max_y, nbins)
        X, Y = np.meshgrid(xlist, ylist)
        Z = func(X, Y)
    else:
        from verticapy.datasets import gen_meshgrid

        vdf_tmp = gen_meshgrid({str_column(columns[1])[1:-1]: {"type": float, "range": [min_y, max_y], "nbins": nbins},
                                       str_column(columns[0])[1:-1]: {"type": float, "range": [min_x, max_x], "nbins": nbins},},
                                       cursor=vdf._VERTICAPY_VARIABLES_["cursor"])
        y = "verticapy_predict"
        if isinstance(func, (str, str_sql,)):
            vdf_tmp["verticapy_predict"] = func
            return(vdf_tmp)
        else:
            if func.type in ("RandomForestClassifier", "NaiveBayes", "NearestCentroid", "KNeighborsClassifier",):
                if func.type in ("NearestCentroid", "KNeighborsClassifier",):
                    vdf_tmp = func.predict(vdf=vdf_tmp, X=columns, name="verticapy_predict", inplace=False, all_classes=True, key_columns=None,)
                    y = "verticapy_predict_{}".format(pos_label)
                else:
                    vdf_tmp = func.predict(vdf=vdf_tmp, X=columns, name="verticapy_predict", pos_label=pos_label)
            else:
                if func.type in ("KNeighborsRegressor",):
                    vdf_tmp = func.predict(vdf=vdf_tmp, X=columns, name="verticapy_predict", inplace=False, key_columns=None,)
                else:
                    
                    vdf_tmp = func.predict(vdf=vdf_tmp, X=columns, name="verticapy_predict",)
        dataset = vdf_tmp[[columns[1], columns[0], y]].sort(columns).to_numpy()
        i, y_start, y_new = 0, dataset[0][1], dataset[0][1]
        n = len(dataset)
        X, Y, Z = [], [], []
    return dataset
```
In the dataset result, the column "verticapy_predict" have NULL values : 

![image](https://user-images.githubusercontent.com/49387599/153005751-cf7106cb-fdd5-4d64-922d-0ba562e69961.png)

Contour doen't work because there are null values in "verticapy_predict" column, but we shouldn't have null value in "verticapy_predict" because, in iris dataset, there aren't null values in ["SepalLengthCm","PetalWidthCm", "PetalLengthCm"] columns. 

Regards,

Alexandre

**Comment by oualib** [comment]
It is very weird as the problem is not coming from the function itself but the model.
I train the model.
```python
from verticapy.learn.tree import DummyTreeRegressor

model = DummyTreeRegressor("model_iris_test2",)
model.drop()
model.fit("iris",["SepalLengthCm","PetalWidthCm"], "PetalLengthCm")
```
I test on the data point: 6.028, 1.204
```sql
SELECT PREDICT_RF_REGRESSOR(6.028, 1.204 
USING PARAMETERS model_name = 'model_iris_test2', match_by_pos = 'true');
```
The result is **NULL**, @afard can you investigate on this?

**Comment by afard** [comment]
It is apparently a bug in Vertica. I'll work on it and resolve it in the next Vertica release.

**Comment by oualib** [comment]
The bug inside Vertica will be corrected in a next Vertica release. In VerticaPy, we will replace the incorrect NULL value by the previous non-NULL value. This function will work properly in the next PR.
