### ISSUE TITLE
KNeighborsClassifier, KNeighborsRegressor method predict

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#223]
Hello,

when we use predict method with KNeighborsClassifier or KNeighborsRegressor with parameter inplace = True, we don't the predict column at the end. 

For exemple with iris dataset : 

![image](https://user-images.githubusercontent.com/49387599/153006882-627d5a15-e295-42d2-8812-caa28db42bb5.png)

On the source code, in predict method you have : 
```
if inplace:
    vdf = self.predict(vdf=vdf,
                       X=X,
                       name=name,
                       inplace=False,
                       cutoff=cutoff,
                       all_classes=all_classes,
                       **kwargs,) 
```

you must put inplace at True.

regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Your solution will create an endless loop. We figure out how to change directly the object inside the code and it will be solved in the next PR.

Thanks for your help
