### ISSUE TITLE
split_polygon_n

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#224]
Hello,

split_polygon_n have an edge effect problem.

With the documentation exemple https://www.vertica.com/python/documentation_last/geo/split_polygon_n/index.php : 

`p = 'POLYGON ((121.334030916 31.5081948415, 121.334030917 31.5079167872, 121.333748304 31.5081948413, 121.334030916 31.5081948415))'
poly = tablesample({"triangle": [p]}).to_vdf()
poly["triangle"].apply("ST_GeomFromText({})")
poly["triangle"].geo_plot(color="white", edgecolor="black")

split_p = split_polygon_n(p)

split_p["geom"].geo_plot(color="white", edgecolor="black")`

we have : 

![image](https://user-images.githubusercontent.com/49387599/153008091-3decb691-a6e7-4e3f-81cc-e6fe2c4d94d1.png)

We show that two squares are shifted.  

When we convert in geopandas the split polygon : 

```
pd_test_split = split_p.to_geopandas(geometry = "geom")[["geom"]]
pd_test_split[["minx", "miny", "maxx", "maxy"]] =  pd_test_split["geom"].bounds
```

we calcul min max on x,y axes : 
![image](https://user-images.githubusercontent.com/49387599/153008470-879fb242-b394-4a4a-82ff-db48831b6d8e.png)

but on the initial figure, we have : 
121.333748304
31.5079167872
121.334030916
31.5081948415

The maximums are differents. 

If we take the second max, we have : 
![image](https://user-images.githubusercontent.com/49387599/153008737-f11094aa-81e6-46f9-be0d-ea9d777e056e.png)

We find the min, max of the initial figure. 

Can you resolve this edge effect problem?

regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,
This problem is a very hard problem to solve in the geospatial space. We can improve the doc to speak about the edge effect. But finding a more precise solution can be very complex.
Badr
