### ISSUE TITLE
sequence cumsum and fillna, cumsum and normalize

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#225]
Hello,

take an exemple with titanic dataset. 

sequence cumsum and fillna function : 

```
titanic_copy = titanic.copy()

titanic_copy.eval("col_1", "1")
titanic_copy.cumsum(column = "col_1", name = "col_id" )
titanic_copy.drop(columns = ["col_1"])

titanic_copy2 = titanic_copy.copy()
titanic_copy2["age"].fillna(val = None, method = "mean", expr = "", by = ["pclass", "sex"], order_by = [])

df_titanic_copy = titanic_copy.to_pandas()
```
when we search col_id = 61 we have : 

![image](https://user-images.githubusercontent.com/49387599/153012091-b0e58a7b-412f-4156-b03b-3c523ee9c14b.png)

I don't understand what append. We are the same problem with sequence cumsum and normalize

Regards, 

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Vertica can not guarantee the order of the data. You should explicitly indicate that you want to sort by something when computing the cumsum. Example:
```python
from verticapy import *
titanic = vDataFrame("titanic")
titanic_copy = titanic.copy()

titanic_copy.eval("col_1", "1")
titanic_copy.cumsum(column = "col_1", name = "col_id", order_by = "name")
titanic_copy.drop(columns = ["col_1"])

titanic_copy2 = titanic_copy.copy()
titanic_copy2["age"].fillna(val = None, method = "mean", expr = "", by = ["pclass", "sex"], order_by = [])
df_titanic_copy = titanic_copy.to_pandas()
```
A parameter "order_by" is most of the time available to allow you to sort your data when using such functions.
