### ISSUE TITLE
sequence cumsum and predict method

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#226]
Hello,

Take an example with titanic dataset and logistic regression : 

```
titanic_copy = titanic.copy()
titanic_copy.eval("col_1", "1")
titanic_copy.cumsum(column = "col_1", name = "col_id" )
titanic_copy.drop(columns = ["col_1"])

from verticapy.learn.linear_model import LogisticRegression
drop(schema + ".lr_titanic", cursor = cur, method = "model")
model = LogisticRegression(name = schema + ".lr_titanic")
model.fit(titanic_copy, ["fare", "age"], "survived")
model.predict(titanic_copy, 
              X = ["fare", "age"],
              name = "prediction_proba",
             inplace = True)
```
show the current relation of titanic_copy : 

![image](https://user-images.githubusercontent.com/49387599/153016486-8ccd5fee-80e0-4bb1-86fd-5a87c209a50d.png)
All seems to be ok. 

use the command : 

`titanic_copy.drop("prediction_proba")`

show the current relation of titanic_copy : 
![image](https://user-images.githubusercontent.com/49387599/153016675-3083a1c5-2461-406b-b1de-48d21802fd33.png)

We have the line : 
     PREDICT_LOGISTIC_REG("fare", "age" USING PARAMETERS model_name = 'DTDSWSP310.lr_titanic', type = 'probability', match_by_pos = 'true') AS "prediction_proba" 

use an other time the command : 

```
model.predict(titanic_copy, 
              X = ["fare", "age"],
              name = "prediction_proba",
             inplace = True)
```

And current relation : 

![image](https://user-images.githubusercontent.com/49387599/153016898-2d47659c-bf99-42b8-8346-a42173fd2ddc.png)

We can't make a loop with predict method if we use cumsum before. 

Regards,,

Alexandre

**Comment by oualib** [comment]
Thanks for reporting this issue. It is corrected and it will be released in the next PR.
