### ISSUE TITLE
NearestCentroid method get_attr

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#227]
Hello,

For NearestCentroid function, I have an error for get_attr method. 

With this code : 

```
from verticapy.learn.neighbors import NearestCentroid

drop(name = schema +".model_titanic_test", cursor = cur, method = "model")
model = NearestCentroid(name = schema +".model_titanic_test", cursor = cur, p = 20)
model.fit(titanic,["age","fare"], "survived")
model.get_attr()
```

I have the following error : 

![image](https://user-images.githubusercontent.com/49387599/153151101-f99bc122-8484-4da3-92b2-e96ea5f5cc59.png)

why?

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Thanks for reporting this bug. It will be corrected in the next release.

Badr
