### ISSUE TITLE
scatter, public schema

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#228]
Hello,

method scatter create temporary view in public schema, but we don't have access to this schema. 

the error is : 
![image](https://user-images.githubusercontent.com/49387599/153153991-55698b37-1f66-46d1-b909-8c42e755fb5d.png)

can you add parameter schema for this method to write temporary object? 

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandr,

The vdf used as input can include the "writing schema".

```python
vdf.set_schema_writing("my_schema")
vdf.scatter(...)
```

I think, we should add a general variable to solve this problem. We will add an extra parameter to the "set_option" function for v0.9.0.

Badr

**Comment by lepelletieralexandre** [comment]
Hello,

We could consider the following scenario:

• By default, the function looks at the vDataFrame passed as a parameter, and retrieves:
    o The schema of the associated table OR the schema of the set_schema_writing parameter
    o They can be potentially different: if the set_schema_writing is specified, it is priority
    o Problem, this is not enough here, because on some functions you can directly pass a table and not a vDataFrame, you would then have to retrieve the schema linked to the table in question
• Then, if set_option is defined, then it takes the given schema
    o This is then applied to all the functions, and replaces/overwrites the other possibilities

It's ok for you? 

Alexandre

**Comment by oualib** [comment]
Are you sure you're using the right version. When reading at the code to build the PCA:
```
if isinstance(dimensions, Iterable):
            model_name = gen_tmp_name(
                schema=verticapy.options["temp_schema"], name="pca_plot"
            )
            from verticapy.learn.decomposition import PCA

            model = PCA(model_name)
```
We can clearly see that the temp schema is used. Can you confirm the issue and the version?

**Comment by lepelletieralexandre** [comment]
it's weird : 

![image](https://user-images.githubusercontent.com/49387599/166449634-af543a3a-18c3-4339-8366-62e2c0e2490a.png)

the problematic line is 8765, but in source code -> https://github.com/vertica/VerticaPy/blob/master/verticapy/vdataframe.py the line is 9345. I have checked and I am in 0.8.1 version on my notebook. 

The version 0.8.1 in conda forge is ok?

Alexandre

**Comment by oualib** [comment]
I checked and it is working for me but I am using the 0.9.0-beta. So in all cases, it will work in the next release.
