### ISSUE TITLE
best_k, public schema

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#237]
Hello,

method best_k create temporary view in public schema, but we don't have access to this schema.

![image](https://user-images.githubusercontent.com/49387599/153155213-20b699a4-57ee-4857-b8c4-efd94b6e666b.png)

can you add parameter schema for this method to write temporary object?

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandr,

The vdf used as input can include the "writing schema".

```python
vdf.set_schema_writing("my_schema")
best_k(vdf)
```

I think, we should add a general variable to solve this problem. We will add an extra parameter to the "set_option" function for v0.9.0.

Badr

**Comment by lepelletieralexandre** [comment]
Hello,

We could consider the following scenario:

• By default, the function looks at the vDataFrame passed as a parameter, and retrieves:
    o The schema of the associated table OR the schema of the set_schema_writing parameter
    o They can be potentially different: if the set_schema_writing is specified, it is priority
    o Problem, this is not enough here, because on some functions you can directly pass a table and not a vDataFrame, you would then have to retrieve the schema linked to the table in question
• Then, if set_option is defined, then it takes the given schema
    o This is then applied to all the functions, and replaces/overwrites the other possibilities

It's ok for you? 

Alexandre
