### ISSUE TITLE
plot_acf_pacf, public schema

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#238]
Hello,

method plot_acf_pacftemporary create temporary view in public schema, but we don't have access to this schema.

![image](https://user-images.githubusercontent.com/49387599/153155383-cfe4a4a1-08a0-493e-90db-9e2983eeff2d.png)

can you add parameter schema for this method to write temporary object?

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandr,

The vdf used as input can include the "writing schema". 
```python
vdf.set_schema_writing("my_schema")
plot_acf_pacf(vdf)
```

I think, we should add a general variable to solve this problem. We will add an extra parameter to the "set_option" function for v0.9.0.

Badr

**Comment by lepelletieralexandre** [comment]
Hello,

We could consider the following scenario:

• By default, the function looks at the vDataFrame passed as a parameter, and retrieves:
    o The schema of the associated table OR the schema of the set_schema_writing parameter
    o They can be potentially different: if the set_schema_writing is specified, it is priority
    o Problem, this is not enough here, because on some functions you can directly pass a table and not a vDataFrame, you would then have to retrieve the schema linked to the table in question
• Then, if set_option is defined, then it takes the given schema
    o This is then applied to all the functions, and replaces/overwrites the other possibilities

It's ok for you? 

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Is it not enough to set the temporary schema at the beginning of the notebook?
```
set_option("temp_schema", "my_temp_schema")
```

Badr

**Comment by lepelletieralexandre** [comment]
hello, 

We think it would be nice to be able to do without set_option in cases where temporary tables can be written in the same schema as our table. it avoids having to use another function to use this function.

Alexandre
