### ISSUE TITLE
AutoClustering, public schema, problem audatapred

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#239]
Hello,

method AutoClustering create table in public schema, but we don't have access to this schema.

with this code : 

```
from verticapy.learn.delphi import AutoClustering

drop(schema + ".titanic_autodataprep", cursor = cur, method = "model")
model = AutoClustering(schema + "titanic_autoClustering",
                     cursor=cur,
                     n_cluster = None,
                     init = "kmeanspp",
                     max_iter = 300,
                     tol = 1e-4,
                     preprocess_data = True,
                     preprocess_dict = {"identify_ts": False, "normalize_min_cat": 0, 
                                              "outliers_threshold": 3.0, "na_method": "drop",},
                     print_info = True,)
model.fit(schema + '.titanic')
```

I have the following error : 

![image](https://user-images.githubusercontent.com/49387599/153157524-657353c7-ffaf-40e0-be9b-9fca6627c873.png)

I think the problem is when autoclustering use audatapred. You write : 

`model_preprocess = AutoDataPrep(cursor=self.cursor, **self.parameters["preprocess_dict"],)`

I think, if you inform "name" parameter, you will solve the problem. 

Regards,

Alexandre

**Comment by oualib** [comment]
Hello Alexandre,

You forgot the "." between the schema and the model name in "AutoClustering" object.

Badr

**Comment by lepelletieralexandre** [comment]
Hello,

exact. I tested with "." and I have the same problem.

Alexandre

**Comment by oualib** [comment]
Indeed, it was solved in the last PR. You can use the "set_option" to change the temp schema.

**Comment by lepelletieralexandre** [comment]
Hello, 

The "set_option" is ok, when I create a first model and fit it, it works. But when I created a new model with the same name and fit it, I have the following error : 

![image](https://user-images.githubusercontent.com/49387599/166204550-a6a2d0ed-ac08-4ba3-89c4-259a6cb61a0d.png)

Before created and fit the second model, I drop the first model with : 
drop(schema + ".titanic_recette_autodataprep", cursor = cur, method = "model")

I think temporary tables in "AutoDataPrep" call are not delete. Can you fix that? 

Alexandre

**Comment by oualib** [comment]
It is not really an issue, as you have to drop the elements created. To make the process easier, we decided to add an option "overwrite_model", if it is set to True the model is overwritten. It will make the functions usage much easier in v0.9.0.
