### ISSUE TITLE
documentation, vDataFrame[].apply

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#240]
Hello,

There is an error in the documentation of vDataFrame[].apply. Parameter "copy" doesn't exist. If we enter a value for "copy_name" parameter, a copy will be created. 

![image](https://user-images.githubusercontent.com/49387599/153164448-d0cfd99d-021b-4af2-b6d4-ecfee186d590.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Thanks for reporting this, the doc will be soon updated.
