### ISSUE TITLE
documentation, cdt

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#241]
Hello,

There is an error in cdt documentation. In the documentation, parameter "columns" is mandatory, but it is optional.

![image](https://user-images.githubusercontent.com/49387599/153164736-38c9c828-e90b-4cfb-a9b6-3cbfe3c2a713.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Thanks for reporting this, the doc will be soon updated.
