### ISSUE TITLE
documentation, regr

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#245]
Hello,

There is an error in regr documentation. method = "cramer" doesn't exist.

![image](https://user-images.githubusercontent.com/49387599/153166006-8a3238da-b467-4b64-a0ec-542b7bc608ef.png)
![image](https://user-images.githubusercontent.com/49387599/153166031-974539c1-8956-4802-8632-8128fc6646e8.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Thanks for reporting this error, the doc will be soon updated.
