### ISSUE TITLE
documentation, sarimax

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#248]
Hello,

There are 2 errors in sarimax documentation. 

First : attributes ma_avg_ is present 2 times, with 2 differents descriptions. 

Second : Features_importance method doesn't workexist : 

![image](https://user-images.githubusercontent.com/49387599/153168468-21152902-d31a-4733-ad75-909440be2427.png)

but in help function, features_importance is present : 

`help(model)`

![image](https://user-images.githubusercontent.com/49387599/153168887-cd54522c-a566-44b0-8081-98a21372df8b.png)

features_importance is present or not? and how use it? 

Regards,

Alexandre

**Comment by oualib** [comment]
Thanks for reporting this doc error. 
SARIMAX has no "features_importance" method. It will be updated in the next doc.
