### ISSUE TITLE
documentation, import plot_acf_pacf

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#249]
Hello,

In documentation, for import function plot_acf_pacf you use : 

`from verticapy.stats import plot_acf_pacf`

but when I use this command : 

![image](https://user-images.githubusercontent.com/49387599/153170599-a2394722-884b-4384-8498-be61d37c038c.png)

where is the function plot_acf_acf? 

Regards,

Alexandre

**Comment by oualib** [comment]
plot_acf_pacf is included in verticapy.learn.model_selection
Thanks for reporting this mistake. The doc will be soon updated.
