### ISSUE TITLE
documentation, MCA

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#252]
Hello,

There are 2 errors in method of MCA documentation.

First : method plot_contrib hasn't parameter "dimension" : 
```
from verticapy.learn.decomposition import MCA
drop(schema + ".mca_iris_titanic", cursor = cur, method = "model")
model = MCA(name = schema + ".mca_iris_titanic")
tcdt = titanic[["survived", "pclass", "sex"]].cdt()
model.fit(tcdt)
model.plot_contrib(dimensions = 1,
              ax=None)
```
![image](https://user-images.githubusercontent.com/49387599/153177751-0896b5ad-d073-4a32-a9d6-8bc558ce3199.png)

but "dimension" parameter is present in help : 

![image](https://user-images.githubusercontent.com/49387599/153177814-93c97229-c25f-4606-822e-71dcaffd9644.png)

Second : in plot_contrib documentation : https://www.vertica.com/python/documentation_last/learn/Model/plot_contrib/ the name of the method is "contrib" not "plot_contrib". 

Regards, 

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

Second point is correct but for the first one the name of the parameter is "dimension" and not "dimensions".

Thanks for your help,

**Comment by lepelletieralexandre** [comment]
Hello,

Thank for the second point and exactly for the first point. But in documentation  : https://www.vertica.com/python/documentation_last/learn/Model/plot_contrib/
dimension"s" is write : 
![image](https://user-images.githubusercontent.com/49387599/155941153-ca814c27-7cdf-4fe0-8276-89dc2ed7d532.png)

Alexandre
