### ISSUE TITLE
random function

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#256]
Hello,

There is a problem with random function. I test the example in documentation : https://www.vertica.com/python/documentation_last/stats/random/index.php

We can see the problem with this code : 

![image](https://user-images.githubusercontent.com/49387599/153844697-e2c5cff5-f721-4a11-8c06-b383714338dd.png)

When we use random function, the column "split" isn't regular. 

We can see the same problem when we create a random column in a vertica table : 

![image](https://user-images.githubusercontent.com/49387599/153845079-3820823f-6955-46a2-a66b-c53479b03e2d.png)

Why the values of random column change in a vdataframe or in tablesample? can you fixed this? 

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandre,

When using the function random, the value will change. It is always the case as long as the value is not saved into a table or temp table. If you want a seeded random, you can use: https://www.vertica.com/python/documentation_last/stats/seeded_random/

But be careful, seeding the randomness can affect the performances.

Best,

badr
