### ISSUE TITLE
Problem with VerticaPy join function (nested requests)

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#257]
We remark a big difference between using joins on View and Vertica Table.   
The problem if the same if we use inner or left join (there is no differences).   

E.g : 
```python
vdf = vfedsite.join(input_relation=vdf, on={"COD_FED": "COD_FED"}, how="left", expr1 = ["COD_FED"], expr2 = [expr1_columns])
```

Here, the left table has 300 000 rows, and the right table 36 rows.    

When we look which requests are generated behind, in using query_profiles in Vertica Catalog, we observe this :    

```sql
INSERT INTO v_temp_schema.VERTICAPY_search_TEST SELECT VERTICAPY_SUBTABLE.IDT_PDE_MES,  
 VERTICAPY_SUBTABLE.COD_PMT_FCN, VERTICAPY_SUBTABLE.COD_FED, VERTICAPY_SUBTABLE.COD_BQE,    
```

```sql
CREATE LOCAL TEMPORARY TABLE VERTICAPY_search_TEST ON COMMIT PRESERVE ROWS AS SELECT * FROM (SELECT * FROM  
  (SELECT "IDT_PDE_MES", "COD_PMT_FCN", "COD_FED", "COD_BQE"   
```

```sql
.TYP_GRP, y.DAT_CRE, y.DAT_MAJ, y.DAT_ALI, y.HEU_ALI, y.TYP_PRD_CMC, y.TYP_USG_PRD, y.NUM_LOC, y.IDT_PI_GLO,   
 y.NUM_TIE_GLO, y.DAT_ARC_REL, y.COD_SYS_GES, y.COD_APN FROM ((SELECT VERTICAPY_SUBTABLE.COD_FED FROM (SELECT   
     VERTICAPY_SUBTABLE.COD_FED FROM (SELECT VDSQZ111_FEDLOC.COD_FED FROM DAQRV0.VDSQZ111_FEDLOC)    
  VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) x LEFT JOIN (SELECT VERTICAPY_SUBTABLE.IDT_PDE_MES, VERTICAPY_SUBTABLE       
```

I give you just some extracts because is very long, but we see, VerticaPy generated many subrequests, in creating temporary tables, which is very expensive.    

Indeed, between VerticaPy Join and the same request in SQL : 

```sql
select * from schemaView.CustomerView tie
inner join schemaView.GeoPrerimeter loc on (tie.COD_FED = loc.COD_FED)
```

We have a big difference in execution time :   
* SQL requests is executed in 2 at 5 seconds
* VerticaPy join takes 20 at 45 minutes (and sometimes the join never finish).    

This problem is also present with the **search** function with the same problem.
Nevertheless, an important precision, this problem is only encountered with view, only when we used views to made joins, but in using tables, the behavior is the same than SQL request directly.    

However, our users use exclusively views, so it's very impactfull because we have to duplicate all data in other schema, to use tables direcly, and then made joins.

**Comment by gaetan-dion** [comment]
Moreover, it could be very useful in expr1 and expr2 in join function, to add the possibility to not select columns, because often, join is just used to made a filter between 2 tables.

**Comment by oualib** [comment]
Hi Gaetan,

When VerticaPy does the join, it creates a temporary table to guess the datatypes. Before it was creating a temp table with 10 lines and it was slowing down the join. Now it will try to guess the types without building a temp table. If it does not succeed, it will create a temp table with 0 row which is instantaneous. [same for the search function]

You need at least to select one column to create the join. What do you mean by not selecting columns? If you don't want to select the columns of one of the 2 expressions, you can set the parameter to None or [].

In the next PR, the joins might become much faster.

Badr

**Comment by gaetan-dion** [comment]
Hi Badr,

Thank you for your feedback!    

By not selecting columns, I mean made a join with 1 or several columns (for inner or left join condition), but it not adding extra columns in the select clause. For example, sometimes we just want to made a join between a left and a right table, to keep rows present in both, but we don't want to select columns from the right table (columns displayed).   
So to do that, we just need to let expr1 or expr2 empty, or to use the key word None.
