### ISSUE TITLE
Dependencies missing in VerticaPy

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#258]
Problem of name conflict with **graphviz** : 
* In PyPI the name is graphviz
* In conda the name is python-graphviz

Because in conda this name is already taken by another library : 
=> This problem is mentionned in this PR : [here](https://github.com/conda-forge/verticapy-feedstock/pull/12)[://](https://github.com/conda-forge/verticapy-feedstock/pull/12)[github.com/conda-forge/verticapy-feedstock/pull/12#issuecomment-986620912](https://github.com/conda-forge/verticapy-feedstock/pull/12)    

Conda is now a standard and the norm for data science, conda is not only a repository, but also a package manager, which goes much further than pip, in resolving all transitive dependencies between all packages, in managing several technologies in same time, such as python, R, NodeJS, etc.    
It's very important now to be ingrated with this technology.       

The **requests-kerberos** dependency is missing also, Vertica and VerticaPy support Kerberos Authentification, but the dependency is not proposed in require or extra_require, from setup.py.

**Comment by oualib** [comment]
@afard please read this article: https://conda-forge.org/docs/maintainer/updating_pkgs.html 
We need to automate the conda update of verticapy.

**Comment by oualib** [comment]
@afard can you please update the conda package from 0.8.0 to 0.8.1? Thanks a lot

**Comment by afard** [comment]
`python-graphviz` and `requests-kerberos` are added to the requirements of the conda package. It is also updated from 0.8.0 to 0.8.1.

**Comment by afard** [comment]
**regro-cf-autotick-bot** automatically creates a PR whenever there is a new release of VerticaPy.
https://github.com/conda-forge/verticapy-feedstock/pull/13
