### ISSUE TITLE
Export results from models or Vertica geograpical function 

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#259]
Some VerticaPy functions trying to export results / files from Vertica cluster, are hardly accessible from users.   
Because users cannot localy access to the system layer, to the different Vertica nodes, this access is reserved for administrators.   

However, we need to get some results like :   
* Cartographical exports : to_shp() : [STV_SetExportShapefileDirectory](https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Geospatial/STV_SetExportShapefileDirectory.htm)

* Model exports : [Link](https://www.vertica.com/docs/10.0.x/HTML/Content/Authoring/SQLReferenceManual/Functions/MachineLearning/EXPORT_MODELS.htm
)
  * PMML
  * Binaires
  * TensorFlow

In this way, Verticapy propose PMML, python or SQL exports, but when the model is very large and dense like random forest or XGBoost, the size of these files are too high.   
So we would need to have a binary export of these files, a serialisation to a binary format.    
And a way to be able to retrieve it.

**Comment by oualib** [comment]
It is a server-side issue and the Vertica team is working on making possible the import/export LOCAL or directly to cloud storage (S3...). We will add it in VerticaPy when it is done. I close this issue for the moment.
