### ISSUE TITLE
pandas_to_vertica - possibility to change the csv path

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#260]
https://github.com/vertica/VerticaPy/blob/master/verticapy/utilities.py#L503   

In this line, pandas_to_vertica function write a temporary csv file, before sending the data to Vertica.   
We need to can choose the path of this file, because sometimes, we don't have access right to the default path.

**Comment by oualib** [comment]
Hi Gaetan,

A new parameter 'temp_path' will be added to the function in the next PR.

Badr
