### ISSUE TITLE
model type 'RandomForest', shapExplainer and to_sklearn

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#261]
Hello,

There are 2 errors in  DecisionTreeClassifier, DummyTreeClassifier, RandomForestClassifier, DecisionTreeRegressor, DummyTreeRegressor, RandomForestRegressor functions.

Methods shapExplainer and to_sklearn don't work : 

![image](https://user-images.githubusercontent.com/49387599/154975390-e8052254-0f07-4b23-bb9d-945b2619a0dd.png)

It's function error or documentation error?

Can you correct that? 

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandr,

The method 'to_sklearn' is deprecated and it is better to use 'to_memmodel' instead. For shapExplainer, we are creating our own function to do it as the shap library is not really compute the "real shap" value. They use multiple linear models to do it, it is then a very brutal approximation. For the moment, shapExplainer is only available for linear models.

Badr
