### ISSUE TITLE
NearestCentroid, methods shapeExplainer and get_attr

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#263]
Hello,

For NearestCentroid model, methods shapeExplainer and get_attr doesn't work.

![image](https://user-images.githubusercontent.com/49387599/154976281-4166771a-460d-4685-ba0d-17bf72c735d6.png)
![image](https://user-images.githubusercontent.com/49387599/154976307-45c90a7d-1bbd-4b3a-9a3a-109c3ab78c75.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Hi Alexandr,

shapeExplainer is not available for this type of models. The issue related to 'get_attr' is duplicated.

Badr
