### ISSUE TITLE
Bug with pandas_to_vertica function - backslash escape character

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#265]
When we use pandas_to_vertica, some files, pandas DataFrame or vDataframe have specials characters inside, like \ (backslash).   
We observe that these lines are not injected in a Vertica table.   

The cause is here : [datasets.py#L245](https://github.com/vertica/VerticaPy/blob/a188213576fa71e5e1623d1cb46fd4f14cc8e41f/verticapy/datasets.py#L245)

The backslash is used like escape character, but if there are some backslash inside the file also, the concerned line(s) can't be injected.   
I advise to nest the copy request between 3 double quotes : """copy ... """

**Comment by oualib** [comment]
Hi Gaetan,

Thanks for reporting the issue.
I changed the default parameter of escape '\\' to '\010' which is the ascii code of \n. In the next PR, this function should work perfectly fine.

Badr

**Comment by oualib** [comment]
Hi Gaetan,

Thanks for reporting the issue.
I changed the default parameter escape in the read_csv function: '\\' to '\027' which is the ascii code of ESC. In the next PR, this function should work perfectly fine.

Badr
