### ISSUE TITLE
Increase km.plot() to same num col at VDB

### ISSUE THREAD

**Issue by liv4unix** [vertica/VerticaPy#271]
Hello;

I have a work around, so this is low priority, but I'm hoping we can get it resolved eventually.

The kmeans.plot() function can only process 1600 columns (verticapy 0.8.0). The Vertica tables that I'm building VerticaPy models against contain image features [pixels] for pre-trained Deep Learning models [~4096 columns] created in PyTorch. It would be great if the VerticaPy kmeans.plot() function could process all columns in the table.  See error below.

Thank you;
Theresa 

QueryError: Severity: ERROR, Message: Problem in creating model [_VERTICAPY_TEMPORARY_PCA_PLOT_MODEL_dbadmin_196110_].
Detail: There are 4096 columns to process. This function cannot yet process more than 1600 columns, Sqlstate: 09000, Routine: processException, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Jackhammer/server/vertica/MachineLearning/MLUtil/ML_Model.cpp, Line: 76, Error Code: 8306, SQL: 'SELECT PCA(\'_VERTICAPY_TEMPORARY_PCA_PLOT_MODEL_dbadmin_196110_\', \'"public"._VERTICAPY_TEMPORARY_VIEW_dbadmin_196110\'

**Comment by oualib** [comment]
Hi Theresa,
Which Vertica version do you have? And which VerticaPy version do you have?
Badr

**Comment by liv4unix** [comment]
Apologies Badr, I thought I included that info.
11.1
0.8.0

**Comment by oualib** [comment]
This limitation is due to Vertica itself. I created a Jira for it.
