### ISSUE TITLE
Tablesample to VDF conversion DateTime Handling Error

### ISSUE THREAD

**Issue by vigneshm1995-Vertica** [vertica/VerticaPy#273]
I am trying to pull data using SQL Magic and convert it to a VDF and run VerticaPy data functions on it.

The result of the SQL query is stored in variable 'x' which is a Tablesample and I am attempting to convert this tablesample to a VDF.

![image](https://user-images.githubusercontent.com/101596043/158244603-44082ec0-c146-4021-b7c2-c2ad912183c9.png)

Is there a better way to do this or a workaround?

**Comment by glarik** [comment]
The issue seems to be here: https://github.com/vertica/VerticaPy/blob/master/verticapy/utilities.py#L1649 (as suggested by the stack trace). math.isnan does not expect a datetime object.

**Comment by oualib** [comment]
You are probably using a previous version. This bug was corrected in v0.7.0.
