### ISSUE TITLE
pandas_to_vertica - insert param lost from 0.6.0 version

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#279]
In 0.5.0 version in VerticaPy, we had an insert param :   
https://www.vertica.com/python/documentation-0.5.0/utilities/pandas_to_vertica/index.php    

This param give the possibility to append rows successively, without load/replace all data each time.    
Indeed, we need to upload rows in a table in append mode, to use loops, etc.

**Comment by oualib** [comment]
Hi Gaetan,

It is available in the last release (0.8.1)

Badr

**Comment by oualib** [comment]
You have also a new function called insert_into which can use any tabular in-memory structure.
