### ISSUE TITLE
once a temp folder is created, I am not able to delete it

### ISSUE THREAD

**Issue by manuchadha1979** [vertica/VerticaPy#285]
Hi

Could you please look at this issue - https://stackoverflow.com/questions/71758213/how-to-delete-temp-table-created-by-verticapy-error-the-table-v-temp-schema

thanks
Manu

**Comment by oualib** [comment]
When the schema is not specified a temporary local table is created. The name of this LTT is then defined by the file name. It is possible to drop this table using the 'drop' function and the 'v_temp_schema'.
```python
from verticapy import drop
drop('v_temp_schema.file_name', method='table')
```
In the next PR, an extra parameter is added to read_csv to generate a name. It will simplify the usage of the function.

**Comment by manuchadha1979** [comment]
Thanks. This works. Just to be clear, `file_name` should be without extension. `drop('v_temp_schema.train', method='table')`
 work but `drop('v_temp_schema.train.csv', method='table' )` will not

**Comment by oualib** [comment]
@manuchadha1979 yes the extension is not used when the table is created.
