### ISSUE TITLE
How to get more than 100 rows in read_csv 

### ISSUE THREAD

**Issue by manuchadha1979** [vertica/VerticaPy#300]
Can you please take a look at 

https://stackoverflow.com/questions/71920495/how-to-get-more-than-100-rows-in-verticapy

**Comment by oualib** [comment]
When looking at the vDataFrame you are looking at the head of the object. If the 100 limit (which is made to avoid loading useless information in memory is not good enough), you can change it using https://www.vertica.com/python/documentation_last/utilities/set_option/ 
```python
from VerticaPy import set_option
set_option('max_rows', 1000)
```
But I really do not recommend it.

Another option is to use directly the head method:
```python
vdd.head(1000)
```
