### ISSUE TITLE
The amount of rows when converting pandas dataframe into a VDF look considerably less than individual pandas dataframe

### ISSUE THREAD

**Issue by manuchadha1979** [vertica/VerticaPy#301]
Can you please look at https://stackoverflow.com/questions/71920553/the-amount-of-rows-when-converting-pandas-dataframe-into-a-vdf-look-considerably

**Comment by oualib** [comment]
Can you please look the number of rows and columns at each step? I really doubt that the function will ingest a so low number of rows.

**Comment by manuchadha1979** [comment]
When I break things down in each step then I see more data. However, if I use combined steps then the problem persists. For example, breaking each of these into separate steps and then using ```pandas_to_vertica``` shows 100 rows

1)
```
train_vdf_to_panda = train_vdf.to_pandas()
train_vdf_to_panda

```

2)
```
test_vdf_to_panda = test_vdf.to_pandas()
test_vdf_to_panda
```

3)
```
combine_list = [test_vdf_to_panda, train_vdf_to_panda]
combine_list

```
4)
```
combine_pdf = pd.concat(combine_list)
combine_pdf

```
5)
```
combine_vdf = pandas_to_vertica(combine_pdf)
combine_vdf 

```
The above works

If I do
1) 
```
import pandas as pd
#combine is a list, but its elements are vDataFrame. concat requires the elements to be Series or DataFrame. So need to convert 
# vdf to panda data frames
combine3 = [train_vdf.to_pandas(), test_vdf.to_pandas()] #gives a list
#type(combine)
combine_pdf3 = pd.concat(combine3)
combine_pdf3

```
The above says 1234 rows × 12 columns

2) 
```
set_option("sql_on", True)
combine_vdf3 = pandas_to_vertica(combine_pdf3)
combine_vdf3

```
The above shows only 2 rows: Rows: 1-2 | Columns: 12

Combining everything into one step also shows only 2 rows

```
import pandas as pd
#combine is a list, but its elements are vDataFrame. concat requires the elements to be Series or DataFrame. So need to convert 
# vdf to panda data frames
combine4 = [train_vdf.to_pandas(), test_vdf.to_pandas()] #gives a list
#type(combine)
combine_pdf4 = pd.concat(combine4)
combine_pdf4
combine_vdf4 = pandas_to_vertica(combine_pdf4)
combine_vdf4
```

**Comment by oualib** [comment]
Can you please run the following:
```python
import pandas as pd
#combine is a list, but its elements are vDataFrame. concat requires the elements to be Series or DataFrame. So need to convert 
# vdf to panda data frames
combine4 = [train_vdf.to_pandas(), test_vdf.to_pandas()] #gives a list
#type(combine)
combine_pdf4 = pd.concat(combine4)
combine_pdf4
print("pandas shape: {}".format(combine_pdf4.shape))
combine_vdf4 = pandas_to_vertica(combine_pdf4)
print("vdf shape: {}".format(combine_pdf4.shape()))
combine_vdf4
```
Thanks

**Comment by manuchadha1979** [comment]
I suppose you mean the following 2nd print - ``` print("vdf shape: {}".format(combine_vdf4.shape)) ```. Calling ```shape ()``` gives error

Pandas shape result

`pandas shape: (1234, 12)`

vdf shape

```
vdf shape: <bound method vDataFrame.shape of      PassengerId    Survived    Pclass      Name                                   Sex       Age   \\
1             62         1.0         1    Icard                          Miss. Amelie    female   \\
2            830         1.0         1    Stone    Mrs. George Nelson (Martha Evelyn)    female   \\
     SibSp    Parch    Ticket      Fare    Cabin    Embarked  
1     38.0        0         0    113572     80.0         B28  
2     62.0        0         0    113572     80.0         B28  
Rows: 1-2 | Columns: 12>
```

**Comment by oualib** [comment]
Please use '.shape()' and not '.shape' when using the vDataFrame. Because the shape of the vDataFrame is a function.

**Comment by manuchadha1979** [comment]
when using ```.shape()```, I get error

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22660/1879121237.py in <module>
      6 combine_pdf4 = pd.concat(combine4)
      7 combine_pdf4
----> 8 print("pandas shape: {}".format(combine_pdf4.shape()))
      9 combine_vdf4 = pandas_to_vertica(combine_pdf4)
     10 print("vdf shape: {}".format(combine_vdf4.shape()))

TypeError: 'tuple' object is not callable


On using ```shape()``` only with ```vdf````, I get the following output

```
import pandas as pd
#combine is a list, but its elements are vDataFrame. concat requires the elements to be Series or DataFrame. So need to convert 
# vdf to panda data frames
combine4 = [train_vdf.to_pandas(), test_vdf.to_pandas()] #gives a list
#type(combine)
combine_pdf4 = pd.concat(combine4)
combine_pdf4
print("pandas shape: {}".format(combine_pdf4.shape))
combine_vdf4 = pandas_to_vertica(combine_pdf4)
print("vdf shape: {}".format(combine_vdf4.shape()))
combine_vdf4
```

output

```
pandas shape: (1234, 12)
vdf shape: (2, 12)
```

**Comment by oualib** [comment]
It seems that the 'escape char' used when ingesting the pandas is not correctly used. This problem will be solved in the next PR. Thanks for reporting the issue.
