### ISSUE TITLE
Adding the possibility to use Jupyter widgets at the top of a vDataFrame [Previous/Next]

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#311]
When displaying a vDataFrame, we can only see the 100 first rows. It would be nice to add a button to move to the next/previous ones. The idea is to create an object at the top of the vDataFrame to do it.

**Comment by dingqiangliu** [comment]
@oualib similarly, could we effect the number of lines returned by SQL Magic ?

**Comment by oualib** [comment]
@dingqiangliu, you'll love the new version of SQL Magic (it has many new options). It will be available soon.
For now, you can use the 'set_option' function to select the number of rows to display.
```python
from vertically.utilities import set_option

set_option('max_rows', 200) # From now, 200 rows will be displayed.
```

**Comment by roypaulin** [comment]
#345

**Comment by PriyankaMF** [comment]
@roypaulin @oualib I see #345 is merged, shall we close this issue and move it to delivered. Please update the status accordingly.

**Comment by roypaulin** [comment]
> @roypaulin @oualib I see #345 is merged, shall we close this issue and move it to delivered. Please update the status accordingly.

No, that PR was not merged to the main branch, I opened another PR to the main branch. We will close this issue when that new PR is merged.

**Comment by roypaulin** [comment]
#353
