### ISSUE TITLE
vdf_from_relation documentation

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#316]
Hello,

In documentation, for vdf_from_relation , schema_writing isn't an argument :

![image](https://user-images.githubusercontent.com/49387599/166206825-d21524d0-17d8-42de-9a2f-daa34704a9a3.png)
Regards,

Alexandre

**Comment by oualib** [comment]
It is corrected and this function is also renamed in the next release. We decided to add an extra parameter sql to vDataFrame to do this operation instead of using this function.

The changes will be visible in v0.9.0
