### ISSUE TITLE
classification report, cutoff nbins

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#318]
hello, 

when you calcul cutoff in classification_report function, you use roc_curve function. In roc_curve function, we can't change the parameter nbins (the default value is 30). 
For titanic exemple, change the nbins at 30 to 100, change the cutoff 0.3666667 -> 0.36, and the exact cutoff is 0.36.
It's not negligible, especiallyon simple dataset like titanic. 

can you give us the possibility to change nbins? 

Alexandre

**Comment by oualib** [comment]
Yes, it can easily be done. We can add it to 0.9.0.
