### ISSUE TITLE
AutoML documentation

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#319]
Hello, 

there are two page for autoML in documentation. 

The first, for "AutoML" : https://www.vertica.com/python/documentation_last/delphi/automl/index.php it's ok

The second for "autoML" : https://www.vertica.com/python/documentation_last/learn/autoML/index.php . But "autoML" function doesn't exist. 

I think the second, "autoML" must be delete? 

Alexandre

**Comment by oualib** [comment]
Yes, it seems to be a server error as I don't see the second one on the doc directory. I will see with the team managing the server how they can erase this page.
