### ISSUE TITLE
gen_meshgrid documentation

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#331]
Hello,

In documentation, for gen_meshgrid, nrows isn't an argument :

![image](https://user-images.githubusercontent.com/49387599/169475471-0e7b24d3-2260-4981-a3c5-31ef641db034.png)

Regards,

Alexandre

**Comment by oualib** [comment]
Thanks for noticing that. It will be corrected in the next doc update (it is already corrected in the doc folder)
