### ISSUE TITLE
method "score" for classification

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#332]
Hello,

There is an inconsistency in "score" method for classification functions. 

In fact, in defaults parameters, you have : method = "accuracy" and cutoff = -1. 

For cutoff definition you have : If the parameter is not between 0 and 1, an automatic cutoff is computed

But in source code, https://github.com/vertica/VerticaPy/blob/master/verticapy/learn/vmodel.py lines 4094-4095 you have : 
`        elif (cutoff >= 1 or cutoff <= 0) and (method != "accuracy"):
            cutoff = self.score("best_cutoff", pos_label, 0.5)`

But for "accuracy" score, we need  a cutoff between 0 and 1, and by default we have a cutoff = -1 and it will not be modified. 

In this "if" condition, why you wrote :  (method != "accuracy")? 

Regards,

Alexandre

**Comment by oualib** [comment]
Hi,

Thanks for reporting the issue.
Which VerticaPy version are you using?

Badr

**Comment by lepelletieralexandre** [comment]
I use version 0.8.1. But I believe the code is the same between 0.8.1 and 0.9.0

Alexandre

**Comment by oualib** [comment]
I think it is better to let the cutoff to 0.5. I created a PR to solve the issue.
