### ISSUE TITLE
features_importance for XGBoostClassifier and XGBoostRegressor

### ISSUE THREAD

**Issue by lepelletieralexandre** [vertica/VerticaPy#333]
Hello,

There is a problem with features_importance méthod for XGBoostClassifier and XGBoostRegressor : 

![image](https://user-images.githubusercontent.com/49387599/169482974-a2e5008e-2e37-41e8-a53c-6daf6867d11f.png)

Regards,

Alexandre

**Comment by oualib** [comment]
@afard or @glarik are we done with the XGB features importance in Vertica?

**Comment by afard** [comment]
For now, feature importance is available only for Random Forest: https://www.vertica.com/docs/11.1.x/HTML/Content/Authoring/SQLReferenceManual/Functions/MachineLearning/RF_PREDICTOR_IMPORTANCE.htm

**Comment by oualib** [comment]
@afard and @glarik I think it is important to implement it as model explainability is really important.
