### ISSUE TITLE
Verticapy sql result footer formatting for Verticapy using pandas dataframe.

### ISSUE THREAD

**Issue by Pavanjreddy** [vertica/VerticaPy#335]
Looks like currently there is no option available to turn off the footer for the sql result coming from Verticapy using pandas dataframe. We need this feature request. Please consider it and implement it at the earliest.

**Comment by oualib** [comment]
Hi Pavanjreddy,
Can you please be more specific? Showing an example would be great

**Comment by Pavanjreddy** [comment]
Hi Badr,

Thanks for the prompt response.

I will send you the details as soon as I get information from our team.

Thanks,
Pavan

**Comment by Pavanjreddy** [comment]
Hi Badr,

I just got the update from the team.

Here is our scenario that needs an option to to disable the footer for a
query result set,

I have a multi-part query that I’m sending in Pandas: “create temp table;
load to temp table; select from table join to temp table”. When Vertica
responds to the initial create temp table statement with a footer, panda
does not recognize that response as a valid result set. This response
pattern is also true for SQL Server, but that platform has the option to
disable footer via a query (‘set nocount on’), which in-turn allows all
statements to complete before responding with a valid dataset. I need that
same option in Vetica.

Thanks,
Pavan

**Comment by oualib** [comment]
Hi Pavanjreddy,

Can you please send me a reproducer so I can understand clearly what you mean by footer? Please use one of the datasets available in VerticaPy to reproduce the error.

Badr

**Comment by Pavanjreddy** [comment]
Hi Badr,

We have a *pset footer off option in VSQL*, we need something similar to
that in VerticaPy when using pandas to remove* (1 row) *display under the
result set. Hope this helps.

select count(*) from sessions;
 count
-------
     5*(1 row)*

dbadmin=> *\pset footer off*
Default footer is off.
dbadmin=> select count(*) from sessions;
 count
-------
     5


Thanks,

Pavan

**Comment by oualib** [comment]
Hi Pavan,

Are you speaking of the vDataFrames (which are not pandas at all) or pandas.DataFrame (in-memory object). For the second one, I can't do anything as I do not have control on the pandas API. For vDataFrames (our own object) we can do it.

So you want an option to remove footer from vDataFrame? Am I correct?

Badr

**Comment by oualib** [comment]
Hi Pavan,

Now you can use the set_option function to choose to display or not display the footer.

```
from verticapy import set_option
set_option('footer_on', False)
```
