### ISSUE TITLE
class_weight for unbalanced dataset

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#343]
Hi,

Most of cases what we study are unbalanced (business, fraud...).   
To correct / rebalance this problem, we use in scikit  ``class_weight = « balanced »``.  

The definition is given here : [scikit link](https://scikit-learn.org/stable/modules/generated/sklearn.utils.class_weight.compute_class_weight.html)    

Formula : n_samples / (n_classes * np.bincount(y))
* n_samples : row number in the dataset.
* n_classes : number of target class (y)
* np_bincount(y) : vector with the occurence number of each y classe .     

It will be very interesting to have this feature in different models.

**Comment by oualib** [comment]
@afard or @glarik do you think we can easily do it in the server side? Otherwise, we can do the sampling manually by creating a temp view.

**Comment by glarik** [comment]
If only calculating the class weights is desired, this should be fairly simple to do with a SQL query. But it seems that @gaetan-dion is looking for algorithm-level weighted data support? If so, we currently don't support this, so I recommend using our existing [BALANCE](https://www.vertica.com/docs/12.0.x/HTML/Content/Authoring/SQLReferenceManual/Functions/MachineLearning/BALANCE.htm) function to rebalance the dataset. It has several options (see the doc linked above) and the user can control what method it uses to balance the data and how aggressively it does so. Hope this helps!

**Comment by oualib** [comment]
It is possible to balance the dataset by using the balance function. We've included some examples for different classifiers. We will close this issue with the corresponding PR. Besides, it is already available for some algorithms like LinearSVC. If it is not enough we can then reopen the issue.
