### ISSUE TITLE
Support for PMML

### ISSUE THREAD

**Issue by thepranj** [vertica/VerticaPy#347]
Currently PMML Model import and predictions are only supported through SQL. Request for this feature via VerticaPy.

For users making PMML models through Python (ex: sklearn), they have to go back and forth between Python and SQL to use the models in Vertica. Having VerticaPy support makes this process more seamless

**Comment by thepranj** [comment]
@oualib @PriyankaMF as discussed

**Comment by oualib** [comment]
What should we do? Currently we support the import and export from the server side. We need to have the 'import local' option to be able to make it easier in VerticaPy.
