### ISSUE TITLE
Small Changes on the vDataFrame interaction

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#354]
I think we can do the following changes:
 - keep the index white
 - The footer is a little bit confusing, it says: "Showing 1 to 25 of 100 entries" whereas the vDataFrame has more entries. Maybe, we can write something more precise?

**Comment by roypaulin** [comment]
I think it refers to max_rows which is set to 100 by default and represents the number of rows that will be displayed. Interactive tables are built on top of vdataframes so they will inherit any display option from them.

**Comment by oualib** [comment]
I got it, please change the message as most of the users will not get it.
