### ISSUE TITLE
Using schema containing dots.

### ISSUE THREAD

**Issue by ryuzakinho** [vertica/VerticaPy#361]
Hei, 

I am using verticaPy version '0.10.0' and Python '3.8.13'

I have a personal schema of the form firstname.lastname@company.com.

I am using verticaPy to train a LinearRegression model as follows:  

```
from verticapy.learn.linear_model import LinearRegression
model = LinearRegression("firstname.lastname@company.com.LR_winequality")
model.fit("public.winequality", ["alcohol"], "quality")
```

This returns the following error:  
```
MissingSchema: Severity: ROLLBACK, Message: Schema "firstname" does not exist
```

I got a similar error when using SQL like this:
```
SELECT LINEAR_REG('firstname.lastname@company.com.myLinearRegModel', 'faithful', 'eruptions', 'waiting' 
                      USING PARAMETERS optimizer='BFGS');
```
Luckily the problem disappears in SQL, when adding "" as follows:
```
SELECT LINEAR_REG('"firstname.lastname@company.com".myLinearRegModel', 'faithful', 'eruptions', 'waiting' 
                      USING PARAMETERS optimizer='BFGS');
```

Unfortunately, the same workaround does not seem to work in verticaPy. Any suggestions around this?

**Comment by oualib** [comment]
Hi,
Thanks for raising this issue.
It is normal as having multiple dots make the schema difficult to identify.
I've tried it in VerticaPy and it works. You should use the same process you're using with Vertica SQL (single quotes outside and double inside).
```python
from verticapy.learn.linear_model import LinearRegression
model = LinearRegression('"firstname.lastname@company.com".LR_winequality')
model.fit("public.winequality", ["alcohol"], "quality")
```
I can close this issue.
Best,
Badr

**Comment by ryuzakinho** [comment]
Hei Badr, 

Thanks a lot for taking the time to reply.

In my original example, I tried to use an example from the document, in my real use case, for some reason, that syntax does not work for me, 

```
# Some SQL query
data = _
model = LinearRegression('"honain.derrar@company.com".LR', solver='BFGS')
model.fit(data, ["VOLUME"], "NET_USD")
```

However, it turns out that this seems to work:

```
# Some SQL query
data = _
model = LinearRegression('"honain.derrar@company.com"."LR"', solver='BFGS')
model.fit(data, ["VOLUME"], "NET_USD")
```

Meaning, by putting the name of the model between "" after the last dot. Trying the option that works in SQL as is returns this:

```ParsingError: The format of the input relation is incorrect.```

Thanks again for your help.
