### ISSUE TITLE
Model Versioning

### ISSUE THREAD

**Issue by PriyankaMF** [vertica/VerticaPy#371]
To integrate model versioning into VerticaPy, we add a new function, named "register", to the VerticaModel class. Calling this function will execute the register_model meta-function inside Vertica and registers the model. We also implement a new class in VerticaPy, named RegisteredModel, in order to work with the registered models inside the database. It may help to look at an easy example before explaining the spec of this class in details.

**An example for registering a model**
model = RandomForestClassifier(name = "my_schema.rfc1")
model.fit("public.train_data", ["pred1","pred2","pred3"], "resp")
model.register("application_name")

rm = mv.RegisteredModel("application_name")

**Comment by oualib** [comment]
when will it be available on the server side?

**Comment by PriyankaMF** [comment]
> when will it be available on the server side?

Please refer to server side spec and design document for details.
