### ISSUE TITLE
Rollup in groupby

### ISSUE THREAD

**Issue by shane-breeze** [vertica/VerticaPy#372]
The vDataFrame.groupby function does not allow rollup of a groupby column. I have tried the following:

```python
import verticapy as vp

iris = vp.read_csv("iris.csv")
iris.groupby("rollup(Species)", "avg(SepalWidthCm)")
```

I received this error:
```
QueryError:
    Severity: ERROR,
    Message: Function rollup(varchar) does not exist, or permission is denied for rollup(varchar),
    Sqlstate: 42883,
    Hint: No function matches the given name and argument types. You may need to add explicit type casts,
    Routine: throwErrorFunctionDoesNotMatch,
    File: <omitted>
    SQL: 'CREATE LOCAL TEMPORARY TABLE "_verticapy_tmp_table_schema_XXX_" ON COMMIT PRESERVE ROWS AS
        SELECT *
        FROM (
            SELECT rollup(Species), avg(SepalWidthCm)
            FROM "v_temp_schema"."_verticapy_tmp_iris_schema_XXX_"
            GROUP BY 1
        ) VERTICAPY_SUBTABLE LIMIT 0'
```

As you can see from the SQL query, it seems that the rollup is being applied in the select clause, hence the error.

Can we change the [groupby function](https://github.com/vertica/VerticaPy/blob/master/verticapy/vdataframe.py#L6425-L6433) to remove the rollup operation on columns in the select clause and then apply the rollup operation for the equivalent column in the groupby clause?

**Comment by oualib** [comment]
Hi @shane-breeze 
A new parameter was added to the groupby method to allow 'rollup'. It will be available for the version 0.10.2.

**Comment by shane-breeze** [comment]
Hi @oualib,
Great, thanks. I had a quick look. Although better than having no rollup option, I have many use cases where only 1 groupby column needs the rollup. Would this functionality be in scope? Possibly allowing a list of True/False for the rollup argument to enable/disable rollup per column

**Comment by oualib** [comment]
@shane-breeze can you please share with me 2 or 3 examples of queries you're running so I can get an idea?

**Comment by shane-breeze** [comment]
My use case is usually to determine time series aggregate statistics split by geography. I want to group by the time series and the geography but I only want to rollup the geography (e.g. the geography could be England, Wales, Scotland and Northern Ireland; the rollup would give me the statistics for the UK). My usual queries look like:
```sql
SELECT month, NVL(geography, 'UK'), count(*)
FROM table
GROUP BY month, rollup(geography)
```

I don't want a rollup of the month as it is not useful.

**Comment by oualib** [comment]
Ok thanks for the answer. The parameter 'rollup' in the groupby method will solve your problem. It will be either a bool or a list of bools. Please upgrade to 0.10.2 when it will be available.

**Comment by oualib** [comment]
v0.10.2 is available and the groupby parameters as well: https://www.vertica.com/python/documentation_last/vdataframe/main-methods/groupby/
