### ISSUE TITLE
Loading Bisecting K-Means

### ISSUE THREAD

**Issue by ruanvt** [vertica/VerticaPy#393]
Hello,

Loading a previously fitted bisecting k-means model does not load all the feature columns.
The first column is omitted, as shown in the example below where the `PetalLengthCm` column is not
included in the loaded model:

```python
from verticapy.learn.cluster import BisectingKMeans
from verticapy.datasets import load_iris

model_name = 'bisecting_k_means'
model = BisectingKMeans(model_name, n_cluster = 3)

iris = load_iris()
model = model.fit(iris, ["PetalLengthCm", "SepalLengthCm"])
print(model.deploySQL())
```
output:
```text
APPLY_BISECTING_KMEANS("PetalLengthCm", "SepalLengthCm" USING PARAMETERS model_name = 'bisecting_k_means', match_by_pos = 'true')
```
Now load the same model and compare:
```python
from verticapy.learn.tools import load_model
loaded_model = load_model(name=model_name)
print(loaded_model.deploySQL())
```
```text
APPLY_BISECTING_KMEANS("SepalLengthCm", 3 USING PARAMETERS model_name = 'bisecting_k_means', match_by_pos = 'true')
```

The problem seems to be in the `load_model` function.
I believe `bisectingkmeans` [here](https://github.com/vertica/VerticaPy/blob/master/verticapy/learn/tools.py#L652) should be `bisecting_kmeans` as used [here](https://github.com/vertica/VerticaPy/blob/master/verticapy/learn/tools.py#L598).

A workaround is to specify the correct feature columns after loading the model:
```python
loaded_model.X = ['"PetalLengthCm"', '"SepalLengthCm"']
print(loaded_model.deploySQL())
```
```text
APPLY_BISECTING_KMEANS("PetalLengthCm", "SepalLengthCm" USING PARAMETERS model_name = 'bisecting_k_means', match_by_pos = 'true')
```

Regards,
Ruan

**Comment by oualib** [comment]
Thanks a lot for submitting this issue. It will be solved in the next PR.
