### ISSUE TITLE
Use geometry type in Vertica

### ISSUE THREAD

**Issue by antoinemertz** [vertica/VerticaPy#441]
Hi,

I try to use the `geometry` in Vertica.
I got one `.shp` file that I read with [geopandas](https://geopandas.org/en/stable/) and then import in a Vertica table.

```
import geopandas as gpd
gdf_communes = gpd.read_file('communes/communes-20220101.shp')
gdf_communes.head()
```
![image](https://user-images.githubusercontent.com/26509655/207064839-5d81242a-d20a-49b1-82f8-43e919e55e87.png)

Then I use the `pandas_to_vertica` function from `verticapy`

```
from verticapy.utilities import pandas_to_vertica
pandas_to_vertica(gdf_communes,
                  cursor=cursor,
                  schema=schema_name,
                  name=table_name)
```

But My table is empty with 0 rows in it and the type of column `geometry` is a `Varchar(92)`. So I also tried to specify the types of the column using `dtype` parameter : 

```
pandas_to_vertica(gdf_communes,
                  cursor=cursor,
                  schema=schema_name,
                  name=table_name,
                  dtype={
                      'insee': 'Varchar(5)',
                      'nom': 'Varchar(70)',
                      'wikipedia': 'Varchar(70)',
                      'surf_ha': 'Numeric(10,2)',
                      'geometry': 'geometry'
                  })
```

But it raises an error:

![image](https://user-images.githubusercontent.com/26509655/207065909-f23ad996-e119-4df7-b12f-637c18811f61.png)

Do you know how I can handle the geometry type in Vertica?

Thanks in advance for your feedback,

Antoine

**Comment by oualib** [comment]
Hi @antoinemertz,

Have you tried to use the 'read_shp' function? But unfortunately the files must be located in the server for this function.

Badr

**Comment by antoinemertz** [comment]
Hi @oualib,
Unfortunatly it is not possible for me to put the files in the server. I also try to ingest the file without the type `geometry` but the columjn as a `Long varchar(130000)`. It works I have a result:
![image](https://user-images.githubusercontent.com/26509655/207859579-abc0dda0-fae6-49b0-acdf-fa5137455ef9.png)

But then I am not able to convert the column to `geometry` type:
```
vdf = vdf.astype({"geometry": "geometry"})
```

![image](https://user-images.githubusercontent.com/26509655/207860070-1ce45ff6-3862-4642-8ce7-f06d138918a6.png)

I'm a bit confused about the error and don't have any idea how to deal with my data.

Antoine

**Comment by oualib** [comment]
Ok, so the only solution I see is to ingest the data as a simple varchar and to then convert it to geometry using STV_GEOMETRY.

I will investigate and see what solution we can bring to this problem. The best one would be to be able to ingest SHP files locally. @afard, @glarik another use-case where we need to be able to ingest SHP locally. I think it is doable as SHP files have a specific format and will not cause security issues. I would say it is important to also have this option for PMMLs.

**Comment by oualib** [comment]
This issue will be solved when Vertica will allow local import of SHP file. Nothing can be done in the VerticaPy side.
