### ISSUE TITLE
Connection password is saved plain text

### ISSUE THREAD

**Issue by villerantanen** [vertica/VerticaPy#458]
User guide suggests using the `verticapy.new_connection()` to connect the database.  It will save the password in ~/.vertica/connections.verticapy  in plain text. Plain text raises a security issue, as in many systems the Vertica password may be the AD password, or anything else. 

Connecting without saving the password should be made easier. 

Based on how the library is built, the following code works, skipping the file writing:
```
verticapy.options["connection"]["conn"] = vertica_python.connect(**connection_parameters)
verticapy.options["connection"]["dsn"] = verticapy.get_connection_file()
verticapy.options["connection"]["section"] = "conn"
```

Feature request:
- Either, wrap that code as verticapy.connect_direct(connection_parameters) and document the plain text passwords
- Or, encrypt the connection file password

**Comment by oualib** [comment]
Hi @villerantanen,

Thank you for reporting this issue. We can hash it before storing it. What do you think?

**Comment by villerantanen** [comment]
yeah, if the documentation explains clearly how to connect without storing credentials (i.e. not using .new_connection()),  then anyone can of course store the user and password info as python variable, and pass them to the connection.

If the library requires them to be shared internally,  perhaps env variables are a good option. I could go with this.

I agree my case is not a typical one, where company has decided to use AD password as Vertica user passwords, instead of creating a separate managed password for the service. In many cases DB passwords are per service, and not per user.  Also, worsening the case, VerticaPy is used in a multi-user cluster, instead of laptops, making the plaintext password slightly worse. 

AFAIK, the next Vertica version will support fallthrough LDAP, in which case the user rights and separate passwords might become an option.

Anyhow,  the ENV variable is a good mitigation to start with.

**Comment by oualib** [comment]
Ok. Let's propose an option with ENV variables in the next release.

[Workaround]
I forgot to mention that you can still connect using any connector manually by using the 'set_connection' function.
https://www.vertica.com/python/documentation_last/connect/set_connection/ 

Nothing will be saved in a file. I think it can solve your problem at the moment. I've added in the 'new_connection' doc more information to explain what we do.

**Comment by villerantanen** [comment]
Thank you
