### ISSUE TITLE
Documentation, read_dsn

### ISSUE THREAD

**Issue by rbensa** [vertica/VerticaPy#459]
Hello, there is a mistake between the description of the read_dsn function here : https://www.vertica.com/python/documentation_last/connect/

And the description here : 
https://www.vertica.com/python/documentation_last/connect/read_dsn/index.php

**Comment by oualib** [comment]
Hi @rbensa 
Thanks for the feedback, we will update the documentation for the next release.

**Comment by oualib** [comment]
The documentation will be generated when the version 1.0.0-beta is shipped. Most of the doc errors will be then corrected.
