### ISSUE TITLE
[Verticapy 0.12.0] Method features_importance for XGBoostClassifier/XGBoostRegressor algortihms

### ISSUE THREAD

**Issue by rbensa** [vertica/VerticaPy#487]
Hello, 

It is not possible to call the features_importance method for XGBoostClassifier and XGBoostRegressor algorithms.

I have found in the source code that those two types are not (yet?) taken into account.

From :
L.348 vmodel.py
`if self.type == "AutoML":`

To :
L.382 vmodel.py
`        elif self.type in (
            "LinearRegression",
            "LogisticRegression",
            "LinearSVC",
            "LinearSVR",
        ):`

So L.411 (vmodel.py) is called :
`            raise FunctionError(
                "Method 'features_importance' for '{}' doesn't exist.".format(self.type)
            )`

Was the omission of types processing of XGBoostClassifier/XGBoostRegressor made voluntarily ?

Kind regards,

Réda

**Comment by oualib** [comment]
Hi @rbensa, please upgrade to the latest VerticaPy release. Which Vertica version do you have?
Features importance for XGB was recently introduced (Vertica 12.0.2 - VerticaPy 0.12.0).

**Comment by rbensa** [comment]
Hello,

The latestest version of Verticapy is installed (0.12.0) but the Vertica version instaled is 11.0.2, however the problem is more about the source code than the Vertica version, the case `self.type == "XGBoostRegressor"` or `self.type == "XGBoostClassifier"` is not processed.

Even if the Vertica 12.0.x version was installed, it would result in the same result (for the Verticapy 0.12.0 version), right ?

Kind regards,

Réda
