### ISSUE TITLE
[Verticapy 0.12] Error with the adjusted-r2 score

### ISSUE THREAD

**Issue by rbensa** [vertica/VerticaPy#490]
Hello,

We are facing a problem concerning the adjusted-r2, specifically when  ``` input_relation=vDataFrame(schema+name) ```.

When `k > 0` the following error is generated :
`ERROR, Message: Syntax error at or near "name"`

Let's have a look at the source code (From L.694 to L.714, metrics.py) : 
```python
    check_types([("k", k, [int]), ("adj", adj, [bool])])
    result = compute_metric_query(
        "RSQUARED({0}, {1}) OVER()",
        y_true,
        y_score,
        input_relation,
        "Computing the R2 Score.",
    )
    if adj and k > 0:
        query = """SELECT /*+LABEL('learn.metrics.r2_score')*/ COUNT(*) FROM {0} 
                   WHERE {1} IS NOT NULL 
                     AND {2} IS NOT NULL;""".format(
            input_relation, y_true, y_score
        )
        n = executeSQL(
            query,
            title="Computing the table number of elements.",
            method="fetchfirstelem",
        )
        result = 1 - ((1 - result) * (n - 1) / (n - k - 1))
    return result

```

When `k = 0` the function `compute_metric_query` is called, there is no problem here as this function can process the case when input_relation is a vDataFrame object (and uses SQL code if it is the case) :

```python
    relation = (
        input_relation
        if isinstance(input_relation, str)
        else input_relation.__genSQL__()
    )
```

However, when `k > 0` the case : `input_relation = vDataFrame(schema+name)` is not processed, and it works great only when `input_relation` is a str instance (schema+name), here is the code (From L.702 to L.712) : 
```python
    if adj and k > 0:
        query = """SELECT /*+LABEL('learn.metrics.r2_score')*/ COUNT(*) FROM {0} 
                   WHERE {1} IS NOT NULL 
                     AND {2} IS NOT NULL;""".format(
            input_relation, y_true, y_score
        )
        n = executeSQL(
            query,
            title="Computing the table number of elements.",
            method="fetchfirstelem",
        )
```

Kind regards,

Réda

**Comment by oualib** [comment]
Thank you @rbensa ,
it will be corrected in the next PR. We are planning on doing more robust tests for this kind of cases in the next version.
