### ISSUE TITLE
[Verticapy 0.12.0] iDisplay Function

### ISSUE THREAD

**Issue by rbensa** [vertica/VerticaPy#509]
Hello,

It is currently not possible to use the iDisplay function, the following error is generated :
`[Errno 2] No such file or directory: '/[...]/verticapy/html/html_template_connected.html'`

The html folder is not present.

I think the problem is in the Setup.py file, the only extensions specified in package_data are : .csv and .json.

.html and .css are not specified.

Kind regards,

Réda

**Comment by oualib** [comment]
Thanks a lot @rbensa,

Indeed, I'm adding this in the next PR.

Best,
