### ISSUE TITLE
[Documentation] Documentation mistakes

### ISSUE THREAD

**Issue by rbensa** [vertica/VerticaPy#525]
Hello, 

Here is a list of errors encountered in the documentation : 

1) https://www.vertica.com/python/documentation_last/learn/Model/multiclass_classification_score/#Model.score-> cutoff is -1 and 0.5 in the source code.

2) https://www.vertica.com/python/documentation_last/learn/memModel/index.php#Parameters -> NearestCentroid**S** (there is an extra "s")

3) https://www.vertica.com/python/documentation_last/vdataframe/main-methods/join/index.php#Example
```Python
flights.join(airlines,
             how = "left",
             on = [("airline": "IATA_CODE", "=")],
             expr1 = ["*"],
             expr2 = ["AIRLINE AS airline_long"])
```
In the third example, it is necessary to replace colons(":") with commas(",")

4) The method  ```Python vDataFrame[].isbool `` is not available (https://www.vertica.com/python/documentation_last/vdataframe/vcolumn-methods/isbool/index.php)

5) https://www.vertica.com/python/documentation_last/vdataframe/main-methods/count_percent/index.php#vDataFrame.count_percent -> It the documentation header "count" is used instead of "count_percent"

Kind regards,

Réda

**Comment by oualib** [comment]
The documentation will be generated when the version 1.0.0-beta is shipped. Most of the doc errors will be then corrected.
