### ISSUE TITLE
[Verticapy 0.12.0] train_test_split method missing values

### ISSUE THREAD

**Issue by rbensa** [vertica/VerticaPy#547]
Hello,

When using the train_test_split method I noticed that there is missing data in some cases.
The approximate_percentile computed here :  https://github.com/vertica/VerticaPy/blob/896cadd29e8c957615aadfe6a0a41d223ca45b6f/verticapy/core/vdataframe/_machine_learning.py#L841 (I know that above is the source code of the 1.0 version, but the case is the same in this version) : 
```Python
        random_func = "SEEDED_RANDOM({})".format(random_seed)
        query = "SELECT /*+LABEL('vDataframe.train_test_split')*/ APPROXIMATE_PERCENTILE({} USING PARAMETERS percentile = {}) FROM {}".format(
            random_func, test_size, self.__genSQL__()
        )
```
is used here https://github.com/vertica/VerticaPy/blob/896cadd29e8c957615aadfe6a0a41d223ca45b6f/verticapy/core/vdataframe/_machine_learning.py#L882 as `q`:

        q = executeSQL(
            query,
            title="Computing the seeded numbers quantile.",
            method="fetchfirstelem",
        )
        test_table = "(SELECT * FROM {} WHERE {} < {}{}) x".format(
            self.__genSQL__(), random_func, q, order_by,
        )
        train_table = "(SELECT * FROM {} WHERE {} > {}{}) x".format(
            self.__genSQL__(), random_func, q, order_by, 

But what if `random_func = q` ?

I had this case for multiple values in a test with the titanic dataset.

Is it possible to add an equal either in the `test_table` query or in the `train_table` query, please ?

Kind regards,

Réda

**Comment by oualib** [comment]
Thanks, this issue will be corrected in the next PR.
