### ISSUE TITLE
[Verticapy 0.12.0] json files not present for laliga dataset

### ISSUE THREAD

**Issue by rbensa** [vertica/VerticaPy#549]
Hello,

I have noticed a problem concerning the laliga dataset.

Altough json extension is correctly present in the `Setup.py` file : 
```Python
package_data={"": ["*.csv", "*.json"]},
```
Those files are not present in the package downloaded from PyPi (pip) : https://pypi.org/project/verticapy/#files

I had previously opened a similar issue for html/css files #509 (those ones were not present in the `Setup.py`), I saw that you have added those extensions in the new `Setup.py` file (for the 1.0 version), however the same problem as the json extension one could occur.

Could you take a look at it, please ?

Thank you,

Kind regards,

Réda

**Comment by oualib** [comment]
I've checked the latest release and the file is correctly located inside the archive, please try to uninstall/reinstall the module.

**Comment by rbensa** [comment]
Hello,

Is it possible to have the download link of the release you are talking about, please ?

Thank you,

Kind regards,

Réda

**Comment by oualib** [comment]
Hi,

Here it is: https://github.com/vertica/VerticaPy/releases/tag/0.12.0

Badr

**Comment by rbensa** [comment]
Hello,

The dataset is available in the release folder (source code), but not in https://pypi.org/project/verticapy/#files (when trying to install it with pip).

Can you take a look at it, please ?

Thank you.

Kind regards,

Réda
