### ISSUE TITLE
Models should not be overwritten by default

### ISSUE THREAD

**Issue by afard** [vertica/VerticaPy#605]
Currently, the "overwrite_model" config parameter determines if a model should be overwritten whenever a new model with same name is trained. The default value of this config parameter is true. This means that users can easily make mistakes and lose their previously archived models inside Vertica DB. IMHO, this is not an appropriate behavior.

My suggestions:
(1) Let's change the default behavior such that the model overwriting would happen only if a user has explicitly asked for it.
(2) Instead of a session scope config parameter, lets make it a model specific parameter. Therefore, it must be explicitly turned on when a vModel object is declared if overwriting behavior is desired for that model name.

**Comment by oualib** [comment]
OK. But it should create a new version of the model. Otherwise, it will make the API not very user friendly.
