### ISSUE TITLE
Add LABEL hints to queries generated by VerticaPy

### ISSUE THREAD

**Issue by bryanherger** [vertica/VerticaPy#607]
We had a request from a Vertica customer to support LABEL hints in queries sent by VerticaPy.  They frequently use service accounts to execute requests and would like users to be able to label their queries so admins can determine who submitted which jobs.  They indicated that a session or connection setting would suffice since all queries from same user/session should have same label for now.

**Comment by thepranj** [comment]
@oualib Hi Badr, here is a product enhancement request from @bryanherger and I's customer. They are a VerticaPy user looking to add query labels through verticapy. Please let us know if there are any questions, thank you.

**Comment by oualib** [comment]
Can you be more specific? a session label is automatically created from the connector: 
```
VERTICAPY_SESSION_LABEL: str = f"verticapy-{__version__}-{VERTICAPY_SESSION_IDENTIFIER}"
```
They can replace it directly using a connection dictionary (field: session_label):
```
vp.new_connection({... "session_label": "my_label" ...})
```

**Comment by bryanherger** [comment]
Client label only identifies the session, and multiple users may use same service account session in the application.  Customer wants to identify who wrote a specific query by adding a hint to the query, e.g. SELECT /*+LABEL(userMLJob*/ ... which they can then track in query_requests table.

**Comment by oualib** [comment]
@bryanherger can you be more specific. Are we talking about SQL magic? Or are we talking about adding a label to all the queries (almost impossible as they follow a specific methodology). Do you have an example?

**Comment by oualib** [comment]
This PR: https://github.com/vertica/VerticaPy/pull/812 will close this issue.

It is adding two new options:
 - label_separator
 - label_suffix

An example can be the following:
```python
from verticapy.datasets import load_titanic
import verticapy as vp

data = load_titanic()
vp.set_option("sql_on", True)
vp.set_option("label_separator", "_____")
vp.set_option("label_suffix", "my_user")
data.avg()
```
The query generated by VerticaPy will look like:
```
Computing the different aggregations.
  SELECT 
    /*+LABEL('vDataframe.aggregate_____my_user')*/ AVG("pclass"), 
    AVG("survived"), 
    AVG("age"), 
    AVG("sibsp"), 
    AVG("parch"), 
    AVG("fare"), 
    AVG("body")   
  FROM 
"public"."titanic" LIMIT 1
```
@bryanherger @thepranj is it enough?
