### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#614]
We need to have an end to end README, from installation to ML. We need to explain everything possible through VerticaPy.
Part to complete:
 - SQL Magic
 - Charts
 - Contributing (another issue is related to this one)
 - Connecting to the Database
 - Quickstart (use the HTML output and show how easy and cool is VerticaPy)

**Comment by mail4umar** [comment]
This was resolved in: Update readme 3 (https://github.com/vertica/VerticaPy/pull/638)
