### ISSUE TITLE
Features Importance Support for XGBoost Models

### ISSUE THREAD

**Issue by thepranj** [vertica/VerticaPy#625]
XGBoost Classifier in VerticaPy does not have the features_importance method. This is a request from a customer who is using this model type. 

![image](https://github.com/vertica/VerticaPy/assets/25474030/a75cafa7-b4eb-4a75-b2f9-a6c08d136dc9)

**Comment by oualib** [comment]
Hi Pranj,

It's already available if you pull the last PR. But I do not recommend to do it at the moment as you might have many backward compatibilities issues.

Badr

**Comment by thepranj** [comment]
Thank you Badr!
