### ISSUE TITLE
Unit Testing - LinearRegression

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#633]
The goal is to find a way to automate unit testing for all linear models.
First step is to look at the old tests located at: tests/vModel/test_linear_regression.py
You can see that we've created many tests for each of the method.

The new test path should be: tests_new/machine_learning/vertica/linear_model/test_linear_regression.py

Then you can look at one of the specific model. For example, Linear Regression.
```python
from verticapy.machine_learning.vertica import LinearRegression
help(LinearRegression)
```
You'll see all the methods and their definition:
```
Methods defined here:
...
predict(self, vdf: Annotated[Union[str, ForwardRef('vDataFrame')], ''], X: Optional[Annotated[Union[str, list[str]], 'STRING representing one column or a list of columns']] = None, name: Optional[str] = None, inplace: bool = True) -> verticapy.core.vdataframe.base.vDataFrame
 |      Predicts using the input relation.
...
```
You have to investigate and test all the methods. For example, the method predict should be tested by using as input 'vdf' a vDataFrame or the string of a relation. So try to test all the possible use-cases. Do not use a very complex dataset as you will have to do many testing. We need to let the tests light. Do not forget that the goal is to increase the code coverage and to identify possible bugs.

For example, you'll have to test the following methods.
```
regression_report
fit
contour
deploySQL
drop
get_attributes
get_params
set_params
summarize
to_python
to_sql
to_memmodel
... [other methods to identify and to test]
```
Use a local fixture to represent the model so you don't have to retrain the model again and again. Also be sure to write optimise tests, as you'll build multiple models with different set of parameters, find a way to not copy paste code and to do some 'kind of loop'.

Besides, for some functions like 'score', you should add some testing to test the score against SKLEARN. For example, if you train a LinearRegression in Vertica and one in SKLEARN with the same input parameters, they should have approximately the same score and the same coefficient. You can define a global variable at the beginning of your file 'TOL=0.05' and you should use it with PYTEST to verify the accuracy of the score.

For each model, you should do the tests with different set of parameters. For example: train with fit_intercept=True and False. Try to use different values for the 'tol' parameter... The goal is to test at least 6 different combination and see if it fits with SKLEARN and that no bug occurs.

**Comment by afard** [comment]
Basically, we have similar tests for all machine-learning models. The similarity increases when we group them to classification, regression, and clustering. Instead of rewriting the same tests for each specific model type, we can consolidate them in a hieratical class structure. @mail4umar has done something similar for the plot tests. You can consult with him.
