### ISSUE TITLE
roc_auc_score unit test for micro and macro averaging

### ISSUE THREAD

**Issue by mail4umar** [vertica/VerticaPy#643]
We need to implement unit tests for the two averaging methods for roc_auc_score for multi-class classification.

**Comment by oualib** [comment]
@vikash018 why is it still open?

**Comment by vikash018** [comment]
@mail4umar - for prc_auc_score with average='weighted' or None or 'score'. We are getting error (
_compute_multiclass_metric() got an unexpected keyword argument 'fun_sql_name'
). can we get proper message saying not implemented?
same goes for roc_auc_score.

**Comment by oualib** [comment]
@vikash018 can you please send a reproducer. It might be the usage of wrong parameters.
