### ISSUE TITLE
vDataFrame.to_csv wrong escape implementation

### ISSUE THREAD

**Issue by xpegenaute** [vertica/VerticaPy#675]
Hi All,

I am trying to generate a CSV file but apparently it is does not escape properly que quote character. Here is an example:
```
vdf = vp.vDataFrame(sql='''SELECT '0' AS ID, 'Comma ", test"' AS DESCR''')
vdf.to_csv('comma_test.csv')
```
It produces:
```
ID","DESCR"
"0","Comma ", test""
```
While it should be :
```
ID,DESCR
0,"Comma "", test"""
```

I am using:
```
vertica-python==1.1.1
verticapy==0.12.0
```

**Comment by oualib** [comment]
Thank you, the bug will be corrected in the next release.
