### ISSUE TITLE
vdf.filter()  silently fails - very dangerous bug

### ISSUE THREAD

**Issue by villerantanen** [vertica/VerticaPy#680]
If .filter commands contain syntax errors, no error is raised, and nothing gets filtered.

example:

```
import verticapy
vdf = verticapy.vDataFrame([[0,0,0]])
vdf.filter(["col1 in (2,3,)"])
```
Command will happily return the 0,0,0 row, and will not raise any errors.  ( the last comma is a syntax error )

likewise,  any syntax error will simply go undetected:

```
import verticapy
vdf = verticapy.vDataFrame([[0,0,0]])
vdf.filter("this simply can't do")
```
returns the whole table again.

**Comment by villerantanen** [comment]
Additionally, IF filtering doesnt filter anything,  it's skipped in the current relation?

```
import verticapy
vdf = verticapy.vDataFrame([[0,0,0]])
vdf = vdf.filter("""
  col0 = 0
""")
print(vdf.current_relation())
```
there is no WHERE in the output here.

**Comment by oualib** [comment]
Hi,

Thank you for raising this issue. Yes, if you filter and nothing is filtered it does not add the SQL into the final relation. To solve this problem we can add an optional parameter in the next release.

For the silent fail, I think it is because of the 'try ... except' used in the code. We will find a better way to implement this part.

Badr

**Comment by oualib** [comment]
<img width="803" alt="Screenshot 2023-10-31 at 20 16 22" src="https://github.com/vertica/VerticaPy/assets/32390048/4a0d16e5-e16b-49f9-b831-365dae73dd46">

A warning is raised in the two first cases.

I've added two new parameters to the function: one to keep the pipeline consistent:

force_filter: bool, optional
            Default Value: True
            When set to True, the vDataFrame will be modified
            even if no filtering occurred. This parameter can
            be used to enforce filtering  and ensure pipeline
            consistency.

Another one to raise the error (and not only the warning):

raise_error: bool, optional
            Default Value: False
            If set to True and the input filtering is incorrect,
            an error is raised.

It will close this issue.
