### ISSUE TITLE
Unexpected results of case_when function

### ISSUE THREAD

**Issue by roni1234** [vertica/VerticaPy#681]
Hi,
I want to add a new column, category, to a dataframe based on the differences between the first 3 values in each group.

I create the following vDataframe:
from verticapy import *
df = tablesample({"x": [2, 3, 16, 33, 7, 12, 10],
                 "key1": [1,1,1,1,5,5,5],
                 "key2": [2,2,2,2,5,5,5]}).to_vdf()
df["x"].astype("float")
display(df)

then run this code:
df_grp = df.groupby(['key1','key2']).case_when("category",
                                                (df['x'][1]-df['x'][0] <= 3) and (df['x'][2]-df['x'][1] < 20), 45, 
                                                (df['x'][1]-df['x'][0] > 20), 4,
                                                 30)
display(df_grp)

The result should be 45 for group (1,2). Reason: (3-2)<=3 and (16-3) < 20 (first condition is met)
and 30 for group (5,5). Reasone: (12-7) > 3 and (12-7) < 20 so the first 2 conditions are not met going to the default 30.

Actually, both groups get always the same result, in this case 45. 
Am I doing something wrong?

**Comment by oualib** [comment]
Hi Roni,

Thanks for mentioning this ambiguous situation.

Your syntax is incorrect.
Please read: https://www.geeksforgeeks.org/difference-between-and-and-in-python/

Also try to use the parenthesis to encapsulate the most important operations. The same should be done using any other pandas modules (like pandas).

Thanks,

Badr

**Comment by roni1234** [comment]
Hi Badr,
Now I understand the problem. I used groupby and in the case_when I used df['x][0] so for all groups it looks at the beginning of the dataframe and not at the beginning of the group. That's why all groups got the same result.
I assume I need to use lambda or something similar but I don't know how.
Please assist
Thanks

**Comment by roni1234** [comment]
I solve this issue using the following code:
df.eval(name="val2", expr="x - lag(x, 1) OVER (PARTITION BY key1, key2 ORDER BY row_num)")
df.eval(name="val1", expr="lag(val2, 1) OVER (PARTITION BY key1,key2 ORDER BY x)")

df = df.filter("row_num = 3")
df_grp = df.case_when("category",
                     (df['val1'] <= 3) & (df['val2'] > 20), 45,
                     (df['val1'] > 20), 4,
                     30)

**Comment by oualib** [comment]
Hi Roni,

As explained in the article the '&' and 'and' operators are different. I am really glad that you successfully solved your issue.

Thanks

Badr
