### ISSUE TITLE
Multiple visual in same plot

### ISSUE THREAD

**Issue by SMoazzamR** [vertica/VerticaPy#7]
Hello Team,
First of all, I would like to thank about this wonderful library which really paced up my working on the whole dataset instead of samples. Now the issue I am facing is that I want to plot multiple visuals in same plot by using a virtual dataframe.

**Comment by oualib** [comment]
Hi SMoazzamR,

Thank you so much for your comment. We are really pleased that this library is helping you. 
For now the Plotting functions are directly showing the graphic and not returning it. You think it would be valuable to add the option of plotting multiple graphics on the same plot? I also think so, it could be added in a future release.

Badr Ouali

**Comment by oualib** [comment]
Now each graphic is returned, so you can use them to draw Multiple visual in same plot.
