### ISSUE TITLE
[Verticapy 0.12.0] nunique function 

### ISSUE THREAD

**Issue by okankcb** [vertica/VerticaPy#719]
Hello,

While using VerticaPy version 0.12.0, it appears that the nunique method produces inaccurate results.

For example, when applying the nunique method to the 'COL_A' column of the 'TABLE_X' table, it returns a value that differs from the actual number of rows in the table. However, the number of unique values should be equivalent to the number of rows, as no duplicates were found when performing a groupby on 'COL_A'.

Here is an example made with the iris dataset :

![image](https://github.com/vertica/VerticaPy/assets/76775516/001f1fd7-ec3b-405b-8b02-d7b794ffc81f)

It is important to note that this issue does not occur with VerticaPy version 0.8.1.

Kind regards,
Okan

**Comment by oualib** [comment]
Hi Okan,

Thank you for your feedback.
COUNT DISTINCT is a very expensive operation, this is why we've implemented the parameter approx.
Please use, nunique(approx = False) to get the exact number of unique elements.

Badr

**Comment by okankcb** [comment]
Thank you so much for your prompt response and for clarifying the use of the approx parameter. I now understand why the function wasn't returning the exact number of unique elements. I will use nunique(approx=False) to get the exact number of unique elements.

Thank you again for your invaluable help.

Okan
