### ISSUE TITLE
Standardize the parameter names for the API functions

### ISSUE THREAD

**Issue by VerticaDataScientist** [vertica/VerticaPy#775]
### Unify the API parameters' names

In certain functions, like `vDataFrame.score()`, the `method` parameter has been modified to `metric`. To maintain consistent parameter names and their intended meanings, I propose updating the following functions where I believe parameter names might need to be changed:

- acf
- corr
- pacf

**Comment by oualib** [comment]
It seems well known API uses 'method' parameter for correlation, I close this issue.
