### ISSUE TITLE
Conda-forge package says VerticaPy 0.12 is not compatible with Python 3.9

### ISSUE THREAD

**Issue by ttk-kstn** [vertica/VerticaPy#807]
Although setup.py states that VerticaPy 0.12 works with Python 3.9 ([Link to setup.py:60](https://github.com/vertica/VerticaPy/blob/532d0f7a7871c3ef88ebaa3768e181133bdc7114/setup.py#L60)) , VerticaPy package distributed from conda-forge says that it requires python<3.9.

![image](https://github.com/vertica/VerticaPy/assets/6270382/2d58b59b-fef4-4191-a4de-b6682eede2eb)

 - [verticapy at conda-forge](https://anaconda.org/conda-forge/verticapy/files)
 - [package info of  noarch/verticapy-0.12.0-pypyhd8ed1ab_0.conda](https://anaconda.org/conda-forge/verticapy/files/modal/info/6395342ba2b71210087a13ba)

As a result, installing VerticaPy fails with conda environment with python 3.9.

```sh
conda create -n my-verticapy -c conda-forge python=3.9 verticapy=0.12
```

Please fix the dependency setting for conda package.

Thanks,

**Comment by oualib** [comment]
@afard can you please fix that?

**Comment by afard** [comment]
I'll investigate.

**Comment by oualib** [comment]
https://github.com/conda-forge/verticapy-feedstock/pull/29

This PR is closing this issue.

**Comment by ttk-kstn** [comment]
That was quick! Thank you.

**Comment by oualib** [comment]
No Problem!
