### ISSUE TITLE
fillna() function lacking an important functionality 

### ISSUE THREAD

**Issue by VerticaDataScientist** [vertica/VerticaPy#814]
Our fillna() function, unlike Pandas, currently doesn't support filling null values with user-specified constants. In Pandas, you can easily fill missing values with the constant of your choice as demonstrated in the example below:

import pandas as pd

data_none = {
    'A': [1, None, 3, None],
    'B': [None, 'Hello', None, 'World']
}
df_none = pd.DataFrame(data_none)
print(df_none)
df_none.fillna(1)
print(df_none)

In our case, the only available function to fill null values is '0ifnull'. However, it has a limitation in that it converts all non-null values to 1, whereas in many cases, we need to keep non-null values as they are.

![fillna](https://github.com/vertica/VerticaPy/assets/118063317/110fb3a7-b7a3-4a0b-959d-26b811704efa)

I believe it would greatly enhance our functionality if we could extend the fillna() function to allow users to specify their desired constant for filling null values. This would provide greater flexibility and compatibility with a broader range of use cases.

**Comment by oualib** [comment]
It is already implemented.
vdf.fillna(1) will for example fill all the missing values by 1. You can choose the constant you want.
