### ISSUE TITLE
Tests - ARIMA / ARMA / AR / MA

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#832]
The goal is to find a way to automate unit testing for all TIME SERIES models.
First step is to look at the linear models tests located at: tests_new/machine_learning/vertica/linear_model/test_linear_regression.py
Tests will be a bit like a regression but a bit more complex.

The new test path should be: tests_new/machine_learning/vertica/tsa/test_arima.py

Then you can look at one of the specific model. For example, ARIMA.
```python
from verticapy.machine_learning.vertica import ARIMA
help(ARIMA)
```
You'll see all the methods and their definition:
```
Methods defined here:
...
predict(self, vdf: Annotated[Union[str, ForwardRef('vDataFrame')], ''], X: Optional[Annotated[Union[str, list[str]], 'STRING representing one column or a list of columns']] = None, name: Optional[str] = None, inplace: bool = True) -> verticapy.core.vdataframe.base.vDataFrame
 |      Predicts using the input relation.
...
```
You have to investigate and test all the methods. For example, the method predict should be tested by using as input 'vdf' a vDataFrame or the string of a relation. So try to test all the possible use-cases. Do not use a very complex dataset as you will have to do many testing. We need to let the tests light. Do not forget that the goal is to increase the code coverage and to identify possible bugs.

For example, you'll have to test the following methods.
```
regression_report
fit
deploySQL
drop
get_attributes
get_params
set_params
summarize
predict
score
... [other methods to identify and to test]
```
Use a local fixture to represent the model so you don't have to retrain the model again and again. Also be sure to write optimise tests, as you'll build multiple models with different set of parameters, find a way to not copy paste code and to do some 'kind of loop'.

Besides, for some functions like 'score', you should add some testing to test the score against SCIPY or STATSMODEL. For example, if you train a ARIMA in Vertica and one in SCIPY / STATSMODEL with the same input parameters, they should have approximately the same score and the same coefficient. You can define a global variable at the beginning of your file 'TOL=0.05' and you should use it with PYTEST to verify the accuracy of the score.

For each model, you should do the tests with different set of parameters. For example: train with order=(1, 0, 0) ... (3, 1, 2). Try to use different values for the 'tol' parameter... The goal is to test at least 6 different combination and see if it fits with SCIPY / STATSMODEL and that no bug occurs.

**Comment by vikash018** [comment]
This issue got close with AR Unit test. 
Reopening this issue as this is linked with other TS algo i.e. MA, ARMA and ARIMA. This issue would ed be closed once all TS unit tests are completed.
