### ISSUE TITLE
ARIMA order issue - d should always be less than 1

### ISSUE THREAD

**Issue by VerticaDataScientist** [vertica/VerticaPy#835]
For ARIMA model it doesn't accept d greater than 0 

This code:

```
from verticapy.machine_learning.vertica.tsa import ARIMA, AR, ARMA, MA
model = ARIMA(name='arima',order = (2,1,2))
model.drop()
model.fit(input_relation=vdf,ts = 'Time',y='Value', test_relation=vdf_test)
pred = model.predict(vdf=vdf_test,ts='Time', y='Value')
```
gives this error:
![d](https://github.com/vertica/VerticaPy/assets/118063317/3535adf0-9294-476f-b881-682f5ac86c27)

**Comment by oualib** [comment]
This is because you have the wrong Vertica version. ARIMA is available since 23.4
