### ISSUE TITLE
Wrong name for value_counts method in documentation

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#86]
Hello,  
   
I think there is a little mistake in the documentation : https://www.vertica.com/python/documentation_last/vdataframe/vcolumn-methods/value_counts/index.php    

In the url and at the bottom of the page, the function name is : value_count**s**, and at the top of the page and in the title the function is called : value_count

Regards

**Comment by oualib** [comment]
Hi Gaetan,

Thank you, it will be solved in the next documentation!
