### ISSUE TITLE
[Unit Testing] Implement Missing Tests for Miscellaneous Cases - Missing

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#897]
Several tests are currently missing and need to be implemented as soon as possible.
 - [x] **feature_engineering:** sessionize, case_when, eval, add_copy, copy.
 - [x] **correlation:** chaid, pivot_table_chi2.
 - [x] **descriptive_statistics:** nlargest, nsmallest, numh.
 - [x] correct model management tests

**Comment by vikash018** [comment]
@oualib - VerticaPy/verticapy/tests/vDataFrame/test_vDF_correlation.py can be deleted now.  chaid, pivot_table_chi2 functions are now covered under new_test VerticaPy/verticapy/tests_new/core/vdataframe/test_machine_learning.py

**Comment by oualib** [comment]
@vikash018 I've added check boxes, please check them when the task is done.

**Comment by oualib** [comment]
Closing this issue as we created another one with missing items.
