### ISSUE TITLE
Pivot / UnPivot Table

### ISSUE THREAD

**Issue by BETEP0K1** [vertica/VerticaPy#9]
With standard Pandas, I can pivot and unpivot dataframe. How can i pivot data using VerticaPy?

This is necessary for example to calculate the correlation matrix later.

**Comment by h-serizawa** [comment]
I guess you are saying about pandas.pivot() function. If I'm wrong, please let me know.

vDataFrame also has pivot_table() function, but it is for data visualization. I'm not sure this is the best answer, but vDataFrame has to_pandas() function to convert vDataFrame to pandas DataFrame. Please be careful as this function copies data into memory.

**Comment by BETEP0K1** [comment]
Thanks for the answer. It will be great to see this functionality in the future

**Comment by h-serizawa** [comment]
Thank you for your feedback. I will discuss this functionality with our team.

**Comment by oualib** [comment]
Hi @BETEP0K1,

The Pivot method is now available. You can upgrade VerticaPy and use the 'help' function to get the parameters.

**Comment by BETEP0K1** [comment]
> Hi @BETEP0K1,
> 
> The Pivot method is now available. You can upgrade VerticaPy and use the 'help' function to get the parameters.

Hi  big thanks!
