### ISSUE TITLE
Vdataframe "schema_writing" ignored while computing KernelDensity model

### ISSUE THREAD

**Issue by FeatCrush** [vertica/VerticaPy#93]
Hello,

We tried to draw a density plot for our Vdataframe but got the error `Permission denied for schema public`
Looking at the error sql query `CREATE  TABLE VERTICAPY_TEMP_MODEL_KDE_%name%_KernelDensity_Map (...)` the function tries to create a table in the public schema which is not allowed in our Vertica setup.
We only authorize users on specific schemas in which they can create new persistent tables. 

Diving into code, the [KernelDensity model seems to always create a persistent table in the public schema](https://github.com/vertica/VerticaPy/blob/master/verticapy/learn/neighbors.py#L1147).
Furthermore, after plotting the density graph, the KernelDensity model is systematically dropped.

With this observations in consideration, i would suggest the following :
* Consider the "schema_writing" Verticapy Variable while generating the `create table` query 
* Add option to use a temporary table instead of a persistent one
* Use temporary tables when model is only use for plotting purposes

I'm quite new to verticapy so feel free to correct or add precisions if I missed something

Regards

Edit: Typo

**Comment by oualib** [comment]
Hi FeatCrush,

Thank you for the feedback.
We will add this option in the next release.

Badr

**Comment by oualib** [comment]
This issue is solved in the version 0.6.0
