### ISSUE TITLE
Bug - cummax function - overwrite original value

### ISSUE THREAD

**Issue by mail4umar** [vertica/VerticaPy#935]
When using ``cummax``, the result overwrites the original values as well as creating a new column. I think either we should not overwrite the original value, or not create a new column.

```
vdf = vp.vDataFrame(
    {
        "sale": [100, 120, 120, 110, 100, 90, 80],
    }
)
vdf.cummax("sale", name = "cummax_sales")
```

**Comment by oualib** [comment]
Please make use of the order_by parameter to sort your data. Otherwise, you might encounter unexpected results, as Vertica does not work with indexes, and the data may be randomly shuffled.
