### ISSUE TITLE
Bug cummin function - automatically orders the list

### ISSUE THREAD

**Issue by mail4umar** [vertica/VerticaPy#936]
When using the cummin function, it automatically orders the list which destroys the purpose of finding the cumulative minimum.

```
vdf = vp.vDataFrame(
    {
        "id": [0, 1, 2, 3, 4, 5, 6],
        "sale": [100, 120, 120, 50, 100, 90, 80],
    }
)
vdf.cummin("sale", name = "cummin_sales")
```
The only way to get meaningful insight is to arrange it using order_by:

```
vdf.cummin("sale", name = "cummin_sales", order_by = "id")
```

**Comment by oualib** [comment]
Please make use of the order_by parameter to sort your data. Otherwise, you might encounter unexpected results, as Vertica does not work with indexes, and the data may be randomly shuffled.
