### ISSUE TITLE
[QPROF] get_cpu_time error 

### ISSUE THREAD

**Issue by beiyuanzhe** [vertica/VerticaPy#939]
qprof.get_cpu_time(chart_type="bar")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [63], line 1
----> 1 qprof.get_cpu_time(chart_type="bar")

File /opt/venv/lib/python3.10/site-packages/verticapy/performance/vertica/qprof.py:1192, in QueryProfiler.get_cpu_time(self, chart_type, reverse, show)
   1190 if show:
   1191     fun = self._get_chart_method(vdf, chart_type)
-> 1192     return fun(columns=columns, method="SUM(counter_value) AS cet")
   1193 return vdf

File /opt/venv/lib/python3.10/site-packages/verticapy/_utils/_sql/_collect.py:159, in save_verticapy_logs.<locals>.func_prec_save_logs(*args, **kwargs)
    156 json_dict = {**json_dict, **kwargs}
    157 save_to_query_profile(name=name, path=path, json_dict=json_dict)
--> 159 return func(*args, **kwargs)

File /opt/venv/lib/python3.10/site-packages/verticapy/core/vdataframe/_plotting.py:378, in vDFPlot.bar(self, columns, method, of, max_cardinality, h, kind, chart, **style_kwargs)
    372 else:
    373     vpy_plt, kwargs = self.get_plotting_lib(
    374         class_name="BarChart2D",
    375         chart=chart,
    376         style_kwargs=style_kwargs,
    377     )
--> 378     return vpy_plt.BarChart2D(
    379         vdf=self,
    380         columns=columns,
    381         method=method,
    382         of=of,
    383         h=h,
    384         max_cardinality=max_cardinality,
    385         misc_layout={"kind": kind},
    386     ).draw(**kwargs)

File /opt/venv/lib/python3.10/site-packages/verticapy/plotting/_plotly/bar.py:118, in BarChart2D.draw(self, fig, **style_kwargs)
    116     fig_base.add_trace(fig)
    117 params = self._update_dict(self.init_layout_style, style_kwargs)
--> 118 fig_base.update_layout(**params)
    119 if self.layout["kind"] == "stacked":
    120     fig_base.update_layout(barmode="stack")

File /opt/venv/lib/python3.10/site-packages/plotly/graph_objs/_figure.py:775, in Figure.update_layout(self, dict1, overwrite, **kwargs)
    749 def update_layout(self, dict1=None, overwrite=False, **kwargs) -> "Figure":
    750     """
    751 
    752     Update the properties of the figure's layout with a dict and/or with
   (...)
    773 
    774     """
--> 775     return super(Figure, self).update_layout(dict1, overwrite, **kwargs)

File /opt/venv/lib/python3.10/site-packages/plotly/basedatatypes.py:1393, in BaseFigure.update_layout(self, dict1, overwrite, **kwargs)
   1369 def update_layout(self, dict1=None, overwrite=False, **kwargs):
   1370     """
   1371     Update the properties of the figure's layout with a dict and/or with
   1372     keyword arguments.
   (...)
   1391         The Figure object that the update_layout method was called on
   1392     """
-> 1393     self.layout.update(dict1, overwrite=overwrite, **kwargs)
   1394     return self

File /opt/venv/lib/python3.10/site-packages/plotly/basedatatypes.py:5113, in BasePlotlyType.update(self, dict1, overwrite, **kwargs)
   5111     with self.figure.batch_update():
   5112         BaseFigure._perform_update(self, dict1, overwrite=overwrite)
-> 5113         BaseFigure._perform_update(self, kwargs, overwrite=overwrite)
   5114 else:
   5115     BaseFigure._perform_update(self, dict1, overwrite=overwrite)

File /opt/venv/lib/python3.10/site-packages/plotly/basedatatypes.py:3920, in BaseFigure._perform_update(plotly_obj, update_obj, overwrite)
   3917                 plotly_obj[key] = val
   3918         else:
   3919             # Assign non-compound value
-> 3920             plotly_obj[key] = val
   3922 elif isinstance(plotly_obj, tuple):
   3924     if len(update_obj) == 0:
   3925         # Nothing to do

File /opt/venv/lib/python3.10/site-packages/plotly/basedatatypes.py:5852, in BaseLayoutType.__setitem__(self, prop, value)
   5849 match = self._subplot_re_match(prop)
   5850 if match is None:
   5851     # Set as ordinary property
-> 5852     super(BaseLayoutHierarchyType, self).__setitem__(prop, value)
   5853 else:
   5854     # Set as subplotid property
   5855     self._set_subplotid_prop(prop, value)

File /opt/venv/lib/python3.10/site-packages/plotly/basedatatypes.py:4850, in BasePlotlyType.__setitem__(self, prop, value)
   4846         self._set_array_prop(prop, value)
   4848     # ### Handle simple property ###
   4849     else:
-> 4850         self._set_prop(prop, value)
   4851 else:
   4852     # Make sure properties dict is initialized
   4853     self._init_props()

File /opt/venv/lib/python3.10/site-packages/plotly/basedatatypes.py:5194, in BasePlotlyType._set_prop(self, prop, val)
   5192         return
   5193     else:
-> 5194         raise err
   5196 # val is None
   5197 # -----------
   5198 if val is None:
   5199     # Check if we should send null update

File /opt/venv/lib/python3.10/site-packages/plotly/basedatatypes.py:5189, in BasePlotlyType._set_prop(self, prop, val)
   5186 validator = self._get_validator(prop)
   5188 try:
-> 5189     val = validator.validate_coerce(val)
   5190 except ValueError as err:
   5191     if self._skip_invalid:

File /opt/venv/lib/python3.10/site-packages/_plotly_utils/basevalidators.py:804, in NumberValidator.validate_coerce(self, v)
    802     if self.has_min_max:
    803         if not (self.min_val <= v <= self.max_val):
--> 804             self.raise_invalid_val(v)
    805 return v

File /opt/venv/lib/python3.10/site-packages/_plotly_utils/basevalidators.py:288, in BaseValidator.raise_invalid_val(self, v, inds)
    285             for i in inds:
    286                 name += "[" + str(i) + "]"
--> 288         raise ValueError(
    289             """
    290     Invalid value of type {typ} received for the '{name}' property of {pname}
    291         Received value: {v}
    292 
    293 {valid_clr_desc}""".format(
    294                 name=name,
    295                 pname=self.parent_name,
    296                 typ=type_str(v),
    297                 v=repr(v),
    298                 valid_clr_desc=self.description(),
    299             )
    300         )

ValueError: 
    Invalid value of type 'builtins.float' received for the 'width' property of layout
        Received value: 0.0

    The 'width' property is a number and may be specified as:
      - An int or float in the interval [10, inf]

**Comment by oualib** [comment]
Seems to be an issue because the table is empty. I will create a PR to catch this type of behaviour.

**Comment by oualib** [comment]
Close it as it seems solved.
