### ISSUE TITLE
Qprof pie chart should show actual value

### ISSUE THREAD

**Issue by beiyuanzhe** [vertica/VerticaPy#948]
![newplot](https://github.com/vertica/VerticaPy/assets/12716903/6e415ee0-3bc4-4779-bee2-2f6631b2ec70)

For example, I want to know the actual value of the biggest part, currently there is no way to do it.

**Comment by mail4umar** [comment]
hey @beiyuanzhe,
if you want to see the absolute values, you can update the plotly trace:

```
plot = qprof.get_qsteps(chart_type="pie")

new_textinfo = 'label+value'
plot.update_traces(textinfo=new_textinfo)

plot.show()
```
