### ISSUE TITLE
qprof very slow because of dc table performance

### ISSUE THREAD

**Issue by beiyuanzhe** [vertica/VerticaPy#949]
When dealing with big dc tables, such as execution_engine_profiles, every operation can take few mins. In my case, the following query took 3 mins, and it was during a live call with customer. Not very fun experience. We should stash the data into real tables and utilize optimized Vertica performance for such queries.

SELECT
     node_name,
     operator_name,
     path_id,
     ROUND(SUM(CASE counter_name WHEN 'execution TIME (us)' THEN counter_value ELSE NULL END) / 1000,
     3.0) AS exec_time_ms,
     SUM(CASE counter_name WHEN 'estimated rows produced' THEN counter_value ELSE NULL END) AS est_rows,
     SUM(CASE counter_name WHEN 'rows processed' THEN counter_value ELSE NULL END) AS proc_rows,
     SUM(CASE counter_name WHEN 'rows produced' THEN counter_value ELSE NULL END) AS prod_rows,
     SUM(CASE counter_name WHEN 'rle rows produced' THEN counter_value ELSE NULL END) AS rle_prod_rows,
     SUM(CASE counter_name WHEN 'consumer stall (us)' THEN counter_value ELSE NULL END) AS cstall_us,
     SUM(CASE counter_name WHEN 'producer stall (us)' THEN counter_value ELSE NULL END) AS pstall_us,
     ROUND(SUM(CASE counter_name WHEN 'memory reserved (bytes)' THEN counter_value ELSE NULL END)/1000000,
     1.0) AS mem_res_mb,
     ROUND(SUM(CASE counter_name WHEN 'memory allocated (bytes)' THEN counter_value ELSE NULL END) / 1000000,
     1.0) AS mem_all_mb
FROM
v_monitor.execution_engine_profiles
WHERE transaction_id=99079191802237466 AND statement_id=7 AND counter_value / 1000000 > 0
GROUP BY 1,
     2,
     3
ORDER BY CASE WHEN SUM(CASE counter_name WHEN 'execution TIME (us)' THEN counter_value ELSE NULL END) IS NULL THEN 1 ELSE 0 END ASC,
     5 DESC

**Comment by oualib** [comment]
@beiyuanzhe , I can add an option to materialise the tables into local temporary tables, is it enough for you? However, you will have to wait a bit to build up the object.
