### ISSUE TITLE
Verbosity of verticapy

### ISSUE THREAD

**Issue by wthomare** [vertica/VerticaPy#952]
Hello,

Due to production restriction, It will be great if the verbosity of vertica/verticapy will be tunable by a parameter and if the actual logs could be ingest by a standard python logger.

The parameter could be set in the connection and have those values : 
- 0 (silent) 
- 1 (warning)
- 2 (info)
- 3 (debug) 

Does this parameter already exist and we missed it ?
Does such a feature is on a roadmap or can we help you ?

Wilfried Thomaré - MLOps

**Comment by oualib** [comment]
@wthomare can you please take time to give us more precision so we can implement a feature which can fit your needs?

**Comment by afard** [comment]
Hello Wilfried,

I'm glad that your message related issues are resolved.
Thanks for your valuable suggestions. We are planning to modernize the logging mechanism of VerticaPy.

Best regards,
Arash

**Comment by oualib** [comment]
@afard do you think you can work on this?

**Comment by afard** [comment]
> @afard do you think you can work on this?

@oualib, I should be able to work on this in the 2nd or the 3rd week of March.
